### ISSUE TITLE
installed all the dependencies and still there is an error it shows with simple_knn 

### ISSUE THREAD

**Issue by jags111** [MrForExample/ComfyUI-3D-Pack#10]
not sure why this and can you pin point to the problem here

```
Traceback (most recent call last):
  File "D:\AI\comfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 13, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GSParams
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 9, in <module>
    from .main_3DGS_renderer import Renderer
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 30, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'

Cannot import D:\AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'simple_knn'
```

**Comment by MrForExample** [comment]
I'll optimize the install method a bit this weekend, seems that's most troublesome part for many users
