### ISSUE TITLE
ComfyUI-3D-Pack fails to load in ComfyUI on Linux system

### ISSUE THREAD

**Issue by drwootton** [MrForExample/ComfyUI-3D-Pack#123]
I tried installing these custom nodes in my Linux ComfyUI installation and the install fails because it cannot find the diff_gaussian_rasterization module. I can't find what module I need to install (pip install ...) so can't complete the install. 
Can you tell me what the correct pip install command is?

Also, I had a previous failure where it could not find the kiui module, which I did resolve by running pip install **kiui** 

The requirements.txt file probably needs to be updated to call out the right modules as well.

**Comment by ksenia-portu** [comment]
@drwootton this issue is duplicate - https://github.com/MrForExample/ComfyUI-3D-Pack/issues/29

**Comment by YanWenKun** [comment]
I opened a PR #126

Or you can just install them from:
https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels

**Comment by drwootton** [comment]
@YanWenKun Thank you for fixing this. I had to rebuild my virtual environment since I was running with python 3.10, now I have it running on python 3.11. I ran a **git cherry-pick** of your commit to add your changes on top of my current ComfyUI. I still get the missing diff_gaussian_rasterization error so I'm probably missing a step. I can't rebuild with docker since I'm apparently missing some GPU driver that is needed. So I'll wait until this gets merged into the main repo and try again.

**Comment by YanWenKun** [comment]
@drwootton hope running this command within container would help:

( this will force-reinstall `diff_gaussian_rasterization`):


```
python3 -m pip install --force-reinstall \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/diff_gaussian_rasterization-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/kiui-0.2.7-py3-none-any.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/nvdiffrast-0.3.1-py3-none-any.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/pointnet2_ops-3.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/pytorch3d-0.7.6-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/simple_knn-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/torchmcubes-0.1.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v1/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl
```

or you can install the compiled binary from another source:

```
python3 -m pip install --force-reinstall \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/diff_gaussian_rasterization-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/nvdiffrast-0.3.1-py3-none-any.whl \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/pointnet2_ops-3.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/pytorch3d-0.7.5-cp311-cp311-linux_x86_64.whl \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/simple_knn-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl \
```

Also I have these packages included in my [Docker image](https://github.com/YanWenKun/ComfyUI-Docker). Hope it works for you!

**Comment by drwootton** [comment]
That was the missing step. I ran that in my virtual environment for ComfyUI and it solved the missing diff_gaussian_rasterization error. Loading then failed because I didn't have xformers installed. I don't know if that's my setup error or if there's a missing requirement in the extension's requirements.txt. **pip install xformers** in my virtual environment. fixed that.
So the workflow for this loads now and runs to completion.
Thanks

**Comment by ksenia-portu** [comment]
@YanWenKun 
this wheel file gives me error. Do you know maybe the reasons behind it?
```
    from diff_gaussian_rasterization import (
  File "path/to/myenv/lib/python3.11/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: path/to/myenv/lib/python3.11/site-packages/diff_gaussian_rasterization/_C.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

**Comment by YanWenKun** [comment]
@ksenia-portu I guess it could be Torch-related, try upgrading it:

```
python3 -m pip install --upgrade \
        xformers torchvision torchaudio \
        --index-url https://download.pytorch.org/whl/cu121 \
        --extra-index-url https://pypi.org/simple
```

**Comment by ksenia-portu** [comment]
@YanWenKun  nope it still gives error:
```
 python
Python 3.11.8 (main, Feb  6 2024, 21:21:21) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import diff_gaussian_rasterization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path_to/diff-gaussian-rasterization/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: cannot import name '_C' from partially initialized module 'diff_gaussian_rasterization' (most likely due to a circular import) (path_to/diff-gaussian-rasterization/diff_gaussian_rasterization/__init__.py)
>>> 
```

**Comment by YanWenKun** [comment]
@ksenia-portu Try install from another compiled wheel:

```
python3 -m pip install --force-reinstall \
  https://github.com/remsky/ComfyUI3D-Assorted-Wheels/raw/main/diff_gaussian_rasterization-0.0.0-cp311-cp311-linux_x86_64.whl
```

**Comment by ksenia-portu** [comment]
These solutions are not working.
This one https://github.com/slbillups/ComfyUI-3D-Pack-troubleshooting_scripts/tree/main/Debian%26Ubuntu gives error:
```
 => CACHED [ 7/21] WORKDIR /app/custom_nodes/ComfyUI-3D-Pack/                                                             0.0s
 => ERROR [ 8/21] COPY --chown=user:user requirements.txt requirements_post.txt ./                                        0.0s
 => ERROR [ 9/21] COPY --chown=user:user simple-knn/ simple-knn/                                                          0.0s
 => ERROR [10/21] COPY --chown=user:user tgs/ tgs/                                                                        0.0s
------                                                                                                                         
 > [ 8/21] COPY --chown=user:user requirements.txt requirements_post.txt ./:
------
------
 > [ 9/21] COPY --chown=user:user simple-knn/ simple-knn/:
------
------
 > [10/21] COPY --chown=user:user tgs/ tgs/:
------
Dockerfile:57
--------------------
  55 |     COPY --chown=user:user requirements.txt requirements_post.txt ./
  56 |     COPY --chown=user:user simple-knn/ simple-knn/
  57 | >>> COPY --chown=user:user tgs/ tgs/
  58 |     RUN pip install --no-cache -r requirements.txt && \
  59 |         pip install --no-cache -r requirements_post.txt && \
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 086d5845-fe13-43e4-aab9-22e7e06614d5::sbcxfmpgsx3iwok4uzcolow6x: "/tgs": not found
```

**Comment by YanWenKun** [comment]
@ksenia-portu I have rebuilt the wheels for better compatibility, try:

```sh
python3 -m pip install --force-reinstall \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/diff_gaussian_rasterization-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/kiui-0.2.7-py3-none-any.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/nvdiffrast-0.3.1-py3-none-any.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/pointnet2_ops-3.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/pytorch3d-0.7.6-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/simple_knn-0.0.0-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/torch_scatter-2.1.2-cp311-cp311-linux_x86_64.whl \
  https://github.com/YanWenKun/ComfyUI-3D-Pack-LinuxWheels/releases/download/v2/torchmcubes-0.1.0-cp311-cp311-linux_x86_64.whl
```

**Comment by YanWenKun** [comment]
By the way, I have these packages pre-installed in the Docker image:
https://github.com/YanWenKun/ComfyUI-Docker

Hope that saves some time for Linux users
