### ISSUE TITLE
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by ken-noland** [MrForExample/ComfyUI-3D-Pack#125]
Hey,

I tried installing ComfyUI-3D-Pack from the Manager inside Comfy, however, I now get the following error:

Traceback (most recent call last):
  File ".\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 30, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File ".\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File ".\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by olegpars** [comment]
Have the same error but did an install with miniconda on a clean comfyui portable setup. Before that had some other modules missing, installed them one after another but when tried to do the same with "pip install diff_gaussian_rasterization" got an error: ERROR: Could not find a version that satisfies the requirement diff_gaussian_rasterization (from versions: none)
ERROR: No matching distribution found for diff_gaussian_rasterization

I attached the full log from miniconda from the moment i started the setup and went through a guide (it was a second try, first one also got messed up)

[log.docx](https://github.com/MrForExample/ComfyUI-3D-Pack/files/14808313/log.docx)

**Comment by ken-noland** [comment]
Yeah, mine was caused by not reading the installation instructions. I'm just going to close this. Sorry @olegpars - you might need to start a new ticket with your issue.

**Comment by olegpars** [comment]
But did you mange to run it?) and did you install through comfyui manager or somehow else?

**Comment by ken-noland** [comment]
Yeah, I got it running. There's a setup script in there that is detailed on the README.md. Make sure you run that and that there are no errors from the installation(I think there was something it complained about, but after I ran it, it worked)

**Comment by olegpars** [comment]
Thank you! I will check it out
