### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#190]
win11+python3.11+miniconda

torchaudio 2.3.1 requires torch==2.3.1, but you have torch 2.3.0+cu121 which is incompatible.
torchvision 0.18.1+cu121 requires torch==2.3.1+cu121, but you have torch 2.3.0+cu121 which is incompatible.
﻿
xformers 0.0.26.post1 requires torch==2.3.0, but you have torch 2.3.1 which is incompatible.

**Comment by saidthebird** [comment]
I managed to got pass by this by manually installing them with in miniconda env. 

`conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

**Comment by saidthebird** [comment]
but then I got stuck on visualstudio error lol

**Comment by 807502278** [comment]
I have completely lowered the versions to solve this problem, but there seems to be a problem with the init of the new version.

**Comment by 807502278** [comment]
> 但是后来我卡在了 visualstudio 错误上，哈哈

You won't report any errors when installing with pip

**Comment by 807502278** [comment]
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
File "D:\AI\ComfyUI-3D\ComfyUI\nodes.py", line 1906, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 50, in <module>
module = importlib.import_module(f".{nodes_filename}", package=__name__)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 50, in <module>
from GaussianSplatting.main_3DGS import GaussianSplatting3D, GaussianSplattingCameraController, GSParams
File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\GaussianSplatting\main_3DGS.py", line 10, in <module>
from .main_3DGS_renderer import GaussianSplattingRenderer
File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\GaussianSplatting\main_3DGS_renderer.py", line 28, in <module>
from simple_knn._C import distCUDA2
ImportError: DLL load failed while importing _C: 找不到指定的程序。
﻿
Cannot import D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: DLL load failed while importing _C: 找不到指定的程序。

**Comment by 807502278** [comment]
I have installed it,
Don't install this, then ninja==1.10.2
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/46019416/c155faf0-5db9-4925-9874-29427debc54e)

**Comment by saidthebird** [comment]
can you share you whole install progress?

**Comment by 807502278** [comment]
Using pip installation:
torch==2.1.2+cu121
torchvision== 0.16.2
torchaudio==2.1.2
xformers ==0.0.23.post1
ninja==1.10.2
Then don't install the local pack on top,There's nothing special about other places

**Comment by 807502278** [comment]
I don't know if there will be any other issues without installing these two local packages. Currently, they can run normally
