### ISSUE TITLE
TypeError: UNetMV2DConditionModel.forward() got an unexpected keyword argument 'dino_feature'

### ISSUE THREAD

**Issue by DreamLoveBetty** [MrForExample/ComfyUI-3D-Pack#194]
The default workflow error for "Era3D_to InstantMesh. json" is as follows:
!!! Exception during processing!!! UNetMV2DConditionModel.forward() got an unexpected keyword argument 'dino_feature'
Traceback (most recent call last):
File "D:\Program\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 2397, in run_model
unet_out = era3d_pipe(
^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Era3D\mvdiffusion\pipelines\pipeline_mvdiffusion_unclip.py", line 585, in call
unet_out = self.unet(
^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UNetMV2DConditionModel.forward() got an unexpected keyword argument 'dino_feature'

**Comment by MrForExample** [comment]
Seems problem is caused by loading other UNetMV2DConditionModel instead of the modified class used by Era3D in `Era3D.mvdiffusion.models.unet_mv2d_condition.py`

Check `Checkpoints\Diffusers\pengHTYX\MacLab-Era3D-512-6view\model_index.json` see if unet attributes is written like following:
```json
  "unet": [
    "Era3D.mvdiffusion.models.unet_mv2d_condition",
    "UNetMV2DConditionModel"
  ],
```

In case you are manually download the checkpoints, please don't overwrite any .json files
