### ISSUE TITLE
 codec can't encode character '\U0001f680' in position 67

### ISSUE THREAD

**Issue by bustrama** [MrForExample/ComfyUI-3D-Pack#198]
Hi all :)
I've just installed fresh portable comfyui + comfyui manager
And installed [ComfyUI-3D-Pack](https://github.com/MrForExample/ComfyUI-3D-Pack)

During the installation, I got this error:
```
[!]  Traceback (most recent call last):
Downloading /include/internal/pycore_import.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_import.h
 [!]Downloading /include/internal/pycore_long.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_long.h
   File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 80, in <module>
 Downloading /include/internal/pycore_list.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_list.h
[!]     cstr("Successfully installed Comfy3D! Let's Accelerate\U0001f680").msg.print()
 Downloading /include/internal/pycore_object.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_object.h
[!]   File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\log_utils.py", line 76, in print
 Downloading /include/internal/pycore_parser.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_parser.h
[!]     print(self, **kwargs)
 Downloading /include/internal/pycore_namespace.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_namespace.h
[!]   File "encodings\cp1252.py", line 19, in encode
 Downloading /include/internal/pycore_opcode.h to E:\AI\ComfyUI_windows_portable\python_embeded/include/internal/pycore_opcode.h
[!] UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 67: character maps to <undefined>
```
From googling I found this lol: U+1F680 ROCKET: 🚀
So I'm not sure where it's in the code but it's probably causing an error

I'm on Windows 11
Updated portable comfyui
Cuda 12.1
I have written all the steps to reproduce above, I'd appreciate if someone can help me solve it 🙏

**Comment by MrForExample** [comment]
Oh no, not the rocket!😅
There is only one place I putted a rocket emoji, is at Line 80 in install.py which called by ComfyUI-Manager after installed requirement.txt, fine, I'll remove it, can't believe this caused a bug for you.

**Comment by bustrama** [comment]
Thank you ❤️
