### ISSUE TITLE
Load CRM MVDiffusion Model error

### ISSUE THREAD

**Issue by jakechai** [MrForExample/ComfyUI-3D-Pack#215]
After the recent update. Found a CRM error for the same workflow and input image.
**The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).**

Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1024 and using 20 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 1024 and using 10 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 5 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 1024 and using 5 heads.
Loaded ViT-H-14 model config.
Loading pretrained ViT-H-14 weights (laion2b_s32b_b79k).
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
--- using zero snr---
!!! Exception during processing!!! The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
Traceback (most recent call last):
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1952, in load_CRM
    crm_mvdiffusion_sampler = get_obj_from_str(crm_config.sampler.target)(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CRM\libs\sample.py", line 32, in __init__
    uc = model.get_learned_conditioning([neg_texts]).to(device)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CRM\imagedream\ldm\interface.py", line 185, in get_learned_conditioning
    return self.clip_model(prompts)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CRM\imagedream\ldm\modules\encoders\modules.py", line 218, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CRM\imagedream\ldm\modules\encoders\modules.py", line 282, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CRM\imagedream\ldm\modules\encoders\modules.py", line 297, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\open_clip\transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\open_clip\transformer.py", line 250, in attention
    return self.attn(
           ^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\modules\activation.py", line 1266, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program Files\ComfyUI_windows_portable_3D\python_embeded\Lib\site-packages\torch\nn\functional.py", line 5382, in multi_head_attention_forward
    raise RuntimeError(f"The shape of the 2D attn_mask is {attn_mask.shape}, but should be {correct_2d_size}.")
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

**Comment by Duodecimus** [comment]
I fixed this by reverting open-clip-torch to version 2.24.0

run this from ComfyUi's update folder
`..\python_embeded\python.exe -s -m pip install open-clip-torch==2.24.0`

**Comment by jakechai** [comment]
> I fixed this by reverting open-clip-torch to version 2.24.0
> 
> run this from ComfyUi's update folder `..\python_embeded\python.exe -s -m pip install open-clip-torch==2.24.0`

Awesome, it works fine, thanks.

**Comment by GitAIUser** [comment]
Error occurred when executing [Comfy3D] Image Add Pure Color Background:

The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 1800, 1440, 3] at index 1

  File "X:\StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 390, in image_add_bg
    image_pils = torch_imgs_to_pils(images, masks)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\StableDiff\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\image_utils.py", line 29, in torch_imgs_to_pils
    images[inv_mask_index] = 0.
    ~~~~~~^^^^^^^^^^^^^^^^

**Comment by jakechai** [comment]
As far as I remember, the resolution value needs to be a multiple of 64.

**Comment by amir84ferdos** [comment]
> python.exe -s -m pip install open-clip-torch==2.24.0

thank you, it worked for me

**Comment by lambertjosh** [comment]
Unfortunately setting `open-clip-torch==2.24.0` did not work for me.  I know this is closed, but its the most commonly referenced issue I can find. Any suggestions on how to fix more recently?

```
  File "/home/xxxxx/projects/ComfyUI/custom_nodes/ComfyUI-3D-Pack/shared_utils/image_utils.py", line 31, in torch_imgs_to_pils
    images[inv_mask_index] = 0.
    ~~~~~~^^^^^^^^^^^^^^^^
IndexError: The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 1024, 1024, 3] at index 1
```

**Comment by mkat2** [comment]
> 64] at index 1

any luck to solve this?

**Comment by DenisKochetov** [comment]
> > 64] at index 1
> 
> any luck to solve this?

maybe the issue with input image, try rgba, rgb, white background
