### ISSUE TITLE
Comfy3D install failed 

### ISSUE THREAD

**Issue by duguyixiaono1** [MrForExample/ComfyUI-3D-Pack#217]
When installing ComfyUI-3D-Pack with comfyui-manager, the error message appears as follow, what's MrForExample/Comfy3D_Pre_Builds?

`Couldn't download folder _Build_Wheels/_Wheels_linux_py312_cu121 from repo MrForExample/Comfy3D_Pre_Builds HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MrForExample/Comfy3D_Pre_Builds (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:983: The handshake operation timed out')))
 [Comfy3D] Try building all required packages...
 [Comfy3D] [Comfy3D BUILD LOG]
 Looking in indexes: http://mirrors.aliyun.com/pypi/simple
   [!] Traceback (most recent call last):
 [!]    File "/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/install.py", line 70, in <module>
[!]      raise RuntimeError("Comfy3D build failed")
 [!] RuntimeError: Comfy3D build failed
          Looking in indexes: https://download.pytorch.org/whl/cu121
                      Looking in indexes: https://download.pytorch.org/whl/cu121
                         Couldn't download folder _Libs from repo MrForExample/Comfy3D_Pre_Builds HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/MrForExample/Comfy3D_Pre_Builds (Caused by ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:983: The handshake operation timed out')))
 
 [Comfy3D] [ERROR] [Comfy3D BUILD ERROR LOG]
 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 Traceback (most recent call last):
   File "/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Scripts/auto_build_all.py", line 124, in <module>
     main(args)
   File "/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Scripts/auto_build_all.py", line 92, in main
     dependencies = read_dependencies(DEPENDENCIES_FILE_ABS_PATH)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Scripts/auto_build_all.py", line 29, in read_dependencies
     raise RuntimeError(f"Comfy3D install failed, couldn't download directory {build_config.libs_dir_name} in remote repository {build_config.repo_id}")
 RuntimeError: Comfy3D install failed, couldn't download directory _Libs in remote repository MrForExample/Comfy3D_Pre_Builds
 
 [Comfy3D] [ERROR] Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.`

**Comment by zafirexd** [comment]
![image](https://github.com/user-attachments/assets/4451311a-bd5f-45f7-92c9-c7e8a37b9a24)

https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11

**Comment by MrForExample** [comment]
@duguyixiaono1 Hi
Seems you have some connection issue with respect to GitHub api or you exceeded the maximum api rate, check your proxy connection if you are using one

**Comment by duguyixiaono1** [comment]
> ![image](https://private-user-images.githubusercontent.com/100502318/348720673-4451311a-bd5f-45f7-92c9-c7e8a37b9a24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjI2MDYsIm5iZiI6MTcyMTEyMjMwNiwicGF0aCI6Ii8xMDA1MDIzMTgvMzQ4NzIwNjczLTQ0NTEzMTFhLWJkNWYtNDVmNy05MmM5LWM3ZThhMzdiOWEyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTMxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzQ2N2I1MTA0NWNiMDRlOGIyZjk5ZjdlNjU5YjE4NTRiMGVjODliOWZmYzBkZWZmY2QzMDg5MDk4ZDE1ODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CQR9gxgCJ_uenTrJItlh1h24qJ_x4KaIOU8zvVxbNbo)
> 
> https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.11

@zafirexd   linux系统呢？

**Comment by zafirexd** [comment]
@duguyixiaono1 I don't know anything about Linux, and its based on Comfyui Portable for windows. 
Ask if anyone has made it works on linux.

私はLinuxについて何も知りません、そしてそれはWindows用のComfyuiPortableに基づいています。
誰かがLinuxでそれを動作させたかどうか尋ねてください。

**Comment by Y-ujl** [comment]
I also encountered this problem, but I carefully looked at build_util.py under _Build_Script file, "_Libs" is only used to store the folder, maybe because of permission problems, the program did not automatically create, so only need to manually create a "_Libs" folder on the line, Same level as _Build_Script
