### ISSUE TITLE
ModuleNotFoundError: No module named 'mvdiffusion'

### ISSUE THREAD

**Issue by YuanXiaoYaoZiZai** [MrForExample/ComfyUI-3D-Pack#218]
hello, I just test workflow (Era3D_to_InstantMesh), but it doesn't work anymore, and other workflow works fine.
I install Comfyui-3D-Pack by Comfyui Manager, and all model already installed automatically.
Show error log in console:
```
!!! Exception during processing!!! No module named 'mvdiffusion'
Traceback (most recent call last):
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1422, in load_diffusers_pipe
    pipe = diffusers_pipeline_class.from_pretrained(
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\python\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 819, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\python\lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 384, in load_sub_model
    class_obj, class_candidates = get_class_obj_and_candidates(
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\python\lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 287, in get_class_obj_and_candidates
    library = importlib.import_module(library_name)
  File "E:\ai\02-ComfyUI\comfyUI-aki-v1.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mvdiffusion'
```

Screenshot
![image](https://github.com/user-attachments/assets/5ecd264c-4528-42b6-99bd-7f4456d8c55d)

![image](https://github.com/user-attachments/assets/cadcf540-7c72-4eba-a33e-293dc1f6e6c3)

Anyone can help me !

**Comment by zafirexd** [comment]
Use the updated workflows located in comfyui/custom nodes/3d-pack/example workflows, and force_download=true

**Comment by MrForExample** [comment]
Hi @YuanXiaoYaoZiZai

1. Check the `Checkpoints\Diffusers\pengHTYX\MacLab-Era3D-512-6view\model_index.json` at line 33, see if it set to     `"Era3D.mvdiffusion.models.unet_mv2d_condition",`
2. You panda image need to have transparent background, otherwise, mask would be none which will cause error

**Comment by YuanXiaoYaoZiZai** [comment]
> 1. Era3D

Thank you for your reply. It has been done

**Comment by YuanXiaoYaoZiZai** [comment]
> Hi @YuanXiaoYaoZiZai
> 
> 1. Check the `Checkpoints\Diffusers\pengHTYX\MacLab-Era3D-512-6view\model_index.json` at line 33, see if it set to     `"Era3D.mvdiffusion.models.unet_mv2d_condition",`
> 2. You panda image need to have transparent background, otherwise, mask would be none which will cause error

Hello @MrForExample ,thanks for your reply. 
I found model_index.json at line 33 from my local:
mvdiffusion.models.unet_mv2d_condition
I fixed it through your guidance like below:
Era3D.mvdiffusion.models.unet_mv2d_condition
Now it's working very well!
