### ISSUE TITLE
I don't know how to fix it, can the author help me, please

### ISSUE THREAD

**Issue by Emeng0911** [MrForExample/ComfyUI-3D-Pack#231]
```
[2024-07-22 23:24] Warn!: Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o 
FAILED: glutil.o 
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o 

```

**Comment by MrForExample** [comment]
@Emeng0911 Hi, please make sure you have installed [Visual Studio Build Tools 2022/2019](https://visualstudio.microsoft.com/downloads/?q=build+tools) with Workloads: Desktop development with C++ (There are a few JIT torch cpp extension that builds in runtime)

**Comment by JimWang151** [comment]
> ```
> [2024-07-22 23:24] Warn!: Traceback (most recent call last):
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
>     subprocess.run(
>   File "subprocess.py", line 571, in run
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
>     module = importlib.import_module(f".{nodes_filename}", package=__name__)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "importlib\__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module>
>     from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list
>   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module>
>     pix2faces_renderer = Pix2FacesRenderer()
>                          ^^^^^^^^^^^^^^^^^^^
>   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__
>     self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
>     self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
>                        ^^^^^^^^^^^^^^^^^^^^
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
>     torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
>     return _jit_compile(
>            ^^^^^^^^^^^^^
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
>     _write_ninja_file_and_build_library(
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
>     _run_ninja_build(
>   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
>     raise RuntimeError(message) from e
> RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o 
> FAILED: glutil.o 
> cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o 
> ```

兄弟，你这个问题解决了吗？怎么解决的？

**Comment by Emeng0911** [comment]
还没有能解决，卡在这里了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月28日(星期六) 晚上8:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MrForExample/ComfyUI-3D-Pack] I don&#39;t know how to fix it, can the author help me, please (Issue #231)














  [2024-07-22 23:24] Warn!: Traceback (most recent call last):   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build     subprocess.run(   File "subprocess.py", line 571, in run subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. The above exception was the direct cause of the following exception: Traceback (most recent call last):   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node     module_spec.loader.exec_module(module)   File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module   File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module&gt;     module = importlib.import_module(f".{nodes_filename}", package=__name__)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "importlib\__init__.py", line 126, in import_module   File "<frozen importlib._bootstrap&gt;", line 1204, in _gcd_import   File "<frozen importlib._bootstrap&gt;", line 1176, in _find_and_load   File "<frozen importlib._bootstrap&gt;", line 1147, in _find_and_load_unlocked   File "<frozen importlib._bootstrap&gt;", line 690, in _load_unlocked   File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module   File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module&gt;     from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module&gt;     pix2faces_renderer = Pix2FacesRenderer()                          ^^^^^^^^^^^^^^^^^^^   File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__     self._glctx = dr.RasterizeGLContext(output_db=False, device=device)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__     self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)                        ^^^^^^^^^^^^^^^^^^^^   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin     torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load     return _jit_compile(            ^^^^^^^^^^^^^   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile     _write_ninja_file_and_build_library(   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library     _run_ninja_build(   File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build     raise RuntimeError(message) from e RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o  FAILED: glutil.o  cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o    
兄弟，你这个问题解决了吗？怎么解决的？

**Comment by JimWang151** [comment]
> 还没有能解决，卡在这里了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年9月28日(星期六) 晚上8:22 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [MrForExample/ComfyUI-3D-Pack] I don&#39;t know how to fix it, can the author help me, please (Issue #231) [2024-07-22 23:24] Warn!: Traceback (most recent call last): File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build subprocess.run( File "subprocess.py", line 571, in run subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module&gt; module = importlib.import_module(f".{nodes_filename}", package=__name__) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "importlib\__init__.py", line 126, in import_module File "<frozen importlib._bootstrap&gt;", line 1204, in _gcd_import File "<frozen importlib._bootstrap&gt;", line 1176, in _find_and_load File "<frozen importlib._bootstrap&gt;", line 1147, in _find_and_load_unlocked File "<frozen importlib._bootstrap&gt;", line 690, in _load_unlocked File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module&gt; from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module&gt; pix2faces_renderer = Pix2FacesRenderer() ^^^^^^^^^^^^^^^^^^^ File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__ self._glctx = dr.RasterizeGLContext(output_db=False, device=device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__ self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx) ^^^^^^^^^^^^^^^^^^^^ File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False) File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load return _jit_compile( ^^^^^^^^^^^^^ File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile _write_ninja_file_and_build_library( File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library _run_ninja_build( File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o FAILED: glutil.o cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -ID:\comfyui\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -DNVDR_TORCH -c D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o 兄弟，你这个问题解决了吗？怎么解决的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我解决了，要不要帮忙？
