### ISSUE TITLE
The semi-automatic building prompt path is too long

### ISSUE THREAD

**Issue by 807502278** [MrForExample/ComfyUI-3D-Pack#240]
I was just curious and tested it : ) After activating the environment(python3.11/cu121/c++17), run “auto_build_all.py”

`ninja: error: Stat(D:/AI/ComfyUI-3D/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Dependencies/pytorch3d/build/temp.win-amd64-cpython-311/Release/AI/ComfyUI-3D/ComfyUI/custom_nodes/ComfyUI-3D-Pack/_Pre_Builds/_Build_Dependencies/pytorch3d/pytorch3d/csrc/ball_query/ball_query.obj): Filename longer than 260 characters`

Additionally, After I ran "install.py", it showed that the installation was successful, yet an error would be given when starting up. 
```
From D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "D:\AI\ComfyUI-3D\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 51, in <module>
    from GaussianSplatting.main_3DGS import GaussianSplatting3D, GaussianSplattingCameraController, GSParams
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\GaussianSplatting\main_3DGS.py", line 10, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\GaussianSplatting\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
  File "D:\AI\ComfyUI-3D\ComfyUI\python_miniconda\Lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: Cannot find the specified program

Cannot import D:\AI\ComfyUI-3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: DLL load failed while importing _C: Cannot find the specified program
```

**Comment by 807502278** [comment]
Perhaps there are other dependencies in my environment that have caused an impact, but I installed and started using the new environment without any problems
