### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found

### ISSUE THREAD

**Issue by Mikerhinos** [MrForExample/ComfyUI-3D-Pack#251]
I'm having this error : 

> Traceback (most recent call last):
  File "D:\pinokio\api\comfyui.git\app\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "D:\pinokio\bin\miniconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 48, in <module>
    from FlexiCubes.flexicubes_trainer import FlexiCubesTrainer
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\flexicubes_trainer.py", line 13, in <module>
    from .loss import sdf_reg_loss
  File "D:\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\MVs_Algorithms\FlexiCubes\loss.py", line 9, in <module>
    import torch_scatter
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\torch_scatter\__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "D:\pinokio\api\comfyui.git\app\env\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\pinokio\bin\miniconda\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] La procédure spécifiée est introuvable

I'm on Win10, none portable version, all the other custom nodes are loading fine :(

**Comment by BoosterCore** [comment]
same here

**Comment by qyyxm99** [comment]
same problem，how to solve？

**Comment by DenisKochetov** [comment]
try to install the latest version from dev branch please
