### ISSUE TITLE
Error installing ComfyUI-3D-Pack via Manager, Windows

### ISSUE THREAD

**Issue by pied-stuff** [MrForExample/ComfyUI-3D-Pack#260]
<img width="1000" alt="3DpackErrors" src="https://github.com/user-attachments/assets/b10acd4f-2d92-49b4-b243-d9a02c3776cc">

**Comment by sjcta** [comment]
same issue

**Comment by mnnbir** [comment]
same issue

**Comment by ammahmoudi** [comment]
just run the following line from the 3d-pack folder and it will be installed: 
`../../../python_embeded/python.exe install.py`

**Comment by pied-stuff** [comment]
> ../../../python_embeded/python.exe install.py
@ammahmoudi 
As mentioned in first post this is windows. I did try your suggestion with all the / changed to \ but still get this error:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
    from build_utils import (
  File "C:\Users\User\Downloads\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\UserPre_Builds/_Build_Scripts\build_utils.py", line 50, in <module>
    CUDA_VERSION = get_cuda_version()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\UserPre_Builds/_Build_Scripts\build_utils.py", line 40, in get_cuda_version
    result = subprocess.run(["nvcc", "--version"], text=True, capture_output=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1509, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 83, in <module>
    cstr("Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.").error.print()
    ^^^^
NameError: name 'cstr' is not defined. Did you mean: 'str'?

**Comment by ammahmoudi** [comment]
@pied-stuff 
Oh I know. My command was also in windows. Don't Change anything. just run it and it will install without the error

**Comment by pied-stuff** [comment]
> @pied-stuff Oh I know. My command was also in windows. Don't Change anything. just run it and it will install without the error

@ammahmoudi 
Wrong, get this error if I try ../../../python_embeded/python.exe install.py:
../../../python_embeded/python.exe install.py
'..' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ammahmoudi** [comment]
@pied-stuff this is me running the command in powershell windows 11: 
![image](https://github.com/user-attachments/assets/eeb75299-6b17-4541-8bec-e0d984f6196a)

**Comment by pied-stuff** [comment]
> @pied-stuff this is me running the command in powershell windows 11: ![image](https://private-user-images.githubusercontent.com/95019899/356803820-eeb75299-6b17-4541-8bec-e0d984f6196a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTg0MzEsIm5iZiI6MTcyMzMxODEzMSwicGF0aCI6Ii85NTAxOTg5OS8zNTY4MDM4MjAtZWViNzUyOTktNmIxNy00NTQxLThiZWMtZTBkOTg0ZjYxOTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE5Mjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTM3ODMzM2M1M2ZhM2VkMmNkZTBlYzJlZDZiYWU5ZTkzYjAxNTcxYmFlYjc1YmRjMWIwMzAzMzMxNWY3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFM_z4obdnMSU9bdohxyzSLbe2Cvq_xzT3NrG5DAXfA)

@ammahmoudi 
Still does not work for me in powershell, get the python cli instead:
../../../python_embeded/python.exe
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
`>>>`

**Comment by pied-stuff** [comment]
> @pied-stuff this is me running the command in powershell windows 11: ![image](https://private-user-images.githubusercontent.com/95019899/356803820-eeb75299-6b17-4541-8bec-e0d984f6196a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTg0MzEsIm5iZiI6MTcyMzMxODEzMSwicGF0aCI6Ii85NTAxOTg5OS8zNTY4MDM4MjAtZWViNzUyOTktNmIxNy00NTQxLThiZWMtZTBkOTg0ZjYxOTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE5Mjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZTM3ODMzM2M1M2ZhM2VkMmNkZTBlYzJlZDZiYWU5ZTkzYjAxNTcxYmFlYjc1YmRjMWIwMzAzMzMxNWY3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFM_z4obdnMSU9bdohxyzSLbe2Cvq_xzT3NrG5DAXfA)
@ammahmoudi 
Does not work. Still get the same error I mentioned above, even in powershell

**Comment by pied-stuff** [comment]
@MrForExample
Any ideas?

**Comment by grAInited** [comment]
> @MrForExample Any ideas?

Hey. Currently wasted 6+hours so far to get a clean comfyui install with just 3D Pack running.

You probably like me, a complete terminal/python noob and struggle with getting the right things running.
Here is a little trick i found:
Just right-click inside a folder where you wanna run/pip something and select "Run Terminal".
The Terminal pops up with the right dir path. Then use "python install.py".
The Terminal will switch to python and runs the install.py inside the 3D-Pack Folder.

Then it should look like in the screenshot from @ammahmoudi 

Maybe it will finish on your PC, but i got again a problem with:
torch -> fbgemm.dll missing dependency and it tries to patch itself
comfy says "(IMPORT FAILED) [ComfyUI-3D-Pack]" i click fix...
Restart, error because of torch/audio/vision wrong version...
again updating... libomp140.x86_64.dll missing or so... or "torchaudio.pyd" blabla
when you delete the "_" from the file "__torchaudio.pyd" then it works again but something else doesn't work and updates...
venv deleted, reinstall everything, path are set... 
INFINITE ERROR LOOP

**Comment by CptJackieSparrow** [comment]
I'm trying to run this with Pinokio on Windows. I get the same issue.
Everything is updated. Trying to install.py as you've said. Lets see what happens.
But it's downloading torch again for some reason. Maybe it's mixed the enviroments. Lets see what happens.

**Comment by meta-meteo** [comment]
> > @pied-stuff Oh I know. My command was also in windows. Don't Change anything. just run it and it will install without the error
> 
> @ammahmoudi Wrong, get this error if I try ../../../python_embeded/python.exe install.py:
> 
> '..' is not recognized as an internal or external command, operable program or batch file.

I get the same error.

In my case, I suspect that because I'm running comfyui on Docker according to "DOCKER_INSTRUCTIONS.md", there are fewer local files and files shared within the container than there are locally stored files, and because the upper levels are not shared within the container, there is no "python_embeded" folder in the first place, and there is no "../../../python_embeded/python.exe" file either. This path cannot be accessed.
So the error occurs.
