### ISSUE TITLE
Gets installed in Ubuntu 23.10, but it won't work

### ISSUE THREAD

**Issue by vicentecarro** [MrForExample/ComfyUI-3D-Pack#27]
I managed to install the custom node from the ComfyUI manager in an updated comfyUI on Ubuntu 23.10 without any errors. However it won't work. ComfyUI signals that it has an import error.

```
## Loading: Workspace Manager (V1.0.0)
### Loading: ComfyUI-Inspire-Pack (V0.63)

[rgthree] Loaded 34 epic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

[comfy_mtb] | INFO -> loaded 63 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://None:8188/mtb if you want more information.
Traceback (most recent call last):
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 26, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-3D-Pack/algorithms/main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-3D-Pack/algorithms/main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import /media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'
```

**Comment by vicentecarro** [comment]
Hmmm, maybe I don't... But does ComfyUi even work without CUDA? In any case I cannot find "nvcc" anywhere, so probably not.

**Comment by al3dv2** [comment]
I'ved this error and after installing cuda 12.1.0 it's fixed the bug this project require a lot of stuff installed

**Comment by MrForExample** [comment]
> I'ved this error and after installing cuda 12.1.0 it's fixed the bug this project require a lot of stuff installed

Thanks for the effort friend.

Yeah, in fact any project of this size would need to install a lot of package, just most of them find a way to install them behind the scene, currently there are a few CUDA packages that is hard to install correctly without build error, my next focus will be make the install as automatic as possible 👍

**Comment by vicentecarro** [comment]
Today I uninstalled it and installed it again, in case any any update could have solved the problems, but it's still failing like before.

**Comment by Falkonar** [comment]
> Today I uninstalled it and installed it again, in case any any update could have solved the problems, but it's still failing like before.

Did you manage to solve it? I have now installed on Debian and still have the same error.

**Comment by vicentecarro** [comment]
> > Today I uninstalled it and installed it again, in case any any update could have solved the problems, but it's still failing like before.
> 
> Did you manage to solve it? I have now installed on Debian and still have the same error.

Nope. I kind of gave up. I think this project is too big (it has too many features) and the myriad of dependencies simply won't install using conventional ways. Someone released recently a custom node for a new 3d method from Nvidia, just one thing, and I managed to have that one working (it wasn't easy though) but this one I cannot make it work (in my own terms, I'm not installing other package managers that are not even in the official repos)

**Comment by Falkonar** [comment]
> > > Today I uninstalled it and installed it again, in case any any update could have solved the problems, but it's still failing like before.
> > 
> > 
> > Did you manage to solve it? I have now installed on Debian and still have the same error.
> 
> Nope. I kind of gave up. I think this project is too big (it has too many features) and the myriad of dependencies simply won't install using conventional ways. Someone released recently a custom node for a new 3d method from Nvidia, just one thing, and I managed to have that one working (it wasn't easy though) but this one I cannot make it work (in my own terms, I'm not installing other package managers that are not even in the official repos)

https://www.youtube.com/watch?v=tYzMYcUty6s
