### ISSUE TITLE
Traceback on run_nvidia_gpu_miniconda.bat

### ISSUE THREAD

**Issue by DeepSkyObjects** [MrForExample/ComfyUI-3D-Pack#28]
I managed to install all requirements, however I get some issues on running the bat.

`Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\__init__.py", line 12, in <module>
    from .webserver.server import server
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\webserver\server.py", line 7, in <module>
    from shared_utils.common_utils import cstr
ModuleNotFoundError: No module named 'shared_utils'

Cannot import C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main module for custom nodes: No module named 'shared_utils'
`

Any missing modules?

**Comment by MrForExample** [comment]
Hi friend, there is a chance that you may git the project before I fixed that issue, I'll make a update pretty soon, feel free to give try,cheers 👍

**Comment by DeepSkyObjects** [comment]
I fixed it manually :), 

@MrForExample 
Are there any glitches concerning to the models folder, I placed it in the ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\checkpoints\lgm but it doesnt seam to load them properly?
Im using the model_fp16.safetensors

**Comment by DeepSkyObjects** [comment]
@MrForExample 
I downloaded the update this morning, got even more problems than earlier. This time the nodes show up as read in comfyUI

`Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\StableDiffusion\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\nodes.py", line 18, in <module>
    from .mesh_processer.mesh import Mesh
  File "C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\mesh_processer\mesh.py", line 11, in <module>
    from shared_utils.sh_utils import SH2RGB
ModuleNotFoundError: No module named 'shared_utils'

Cannot import C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main module for custom nodes: No module named 'shared_utils'
### Loading: ComfyUI-Impact-Pack (V4.75)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Manager (V2.7.2)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 1943 [eeca7248] | Released on '2024-01-31'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Import times for custom nodes:
   0.3 seconds: C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds (IMPORT FAILED): C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main
   0.5 seconds: C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json`

**Comment by DeepSkyObjects** [comment]
Oh so the issue was that I didnt pull it directly from git, downloaded it as a zipfile and then it added main to the foldername to reflect the branch when I tried to update it manually....

Looks like its working now :).

**Comment by xenonjargarta** [comment]
Hey there,
I fixed it on my side by removing the -main in the folder name.

Regards

Marcus
