### ISSUE TITLE
Challange with No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by xenonjargarta** [MrForExample/ComfyUI-3D-Pack#29]
Hey everyone,

I tried the the last 3 days of commits and it ends up in the fail below. 

"diff_gaussian_rasterization" First question is this a custom (developer module)?

Regards

Marcus

File "H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 26, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import H:\Programme\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'

**Comment by Kobak24** [comment]
got same error today! 
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by MrForExample** [comment]
Can you please give me the command & steps you used for installed, I can't help you to debug with only the last error

**Comment by Kobak24** [comment]
I've just installed from comfyui manager and reloaded/refreshed everything.

Here are some other info if those may help:
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.2+cu121
 ComfyUI startup time: 2024-02-12 21:04:41.408370
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
diffusers:  0.26.2

Here's the full error:
Traceback (most recent call last):
  File "E:\_AI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\_AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\******\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\_AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 26, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "E:\_AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "E:\_AI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

**Comment by MrForExample** [comment]
Seems you are not miniconda/conda env when running the ComfyUI.

Have you run the `install.bat` or `pip install -r requirements_post.txt` in your miniconda/conda env? Did get any build error?
If you didn't get any error, then please check [run instruction](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#run)

**Comment by filliptm** [comment]
is it required to run a conda env? im running the non portable version of comfy, pip installed your req.txt, getting this error still

**Comment by drwootton** [comment]
I am running a copy of ComfyUI I installed on my Linus system manually, without anaconda/conda. Everything else I installed in ComfyUI works without conda and other AI software works as well. Why is conda required? I don't understand what it adds beyond the Python virtual environment I set up with venv.
How can I fix this without having anything to do with conda?
