### ISSUE TITLE
TypeError: _get_model_file() got an unexpected keyword argument 'resume_download'

### ISSUE THREAD

**Issue by RainEmy** [MrForExample/ComfyUI-3D-Pack#303]
感谢作者开源，不知是否有空看一下这段报错。
!!! Exception during processing !!! _get_model_file() got an unexpected keyword argument 'resume_download'
Traceback (most recent call last):
  File "E:\sd-webui-aki-v4.3\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\sd-webui-aki-v4.3\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 3034, in load_model
    character_mv_gen_pipe = Inference2D_API(checkpoint_root_path=self.checkpoints_dir_abs, **OmegaConf.load(self.config_root_path_abs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CharacterGen\character_inference.py", line 112, in __init__
    unet = UNetMV2DConditionModel.from_pretrained_2d(pretrained_model_path, subfolder="unet", local_crossattn=local_crossattn, **unet_from_pretrained_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CharacterGen\Stage_2D\tuneavideo\models\unet_mv2d_condition.py", line 1302, in from_pretrained_2d
    model_file = _get_model_file(
                 ^^^^^^^^^^^^^^^^
  File "E:\sd-webui-aki-v4.3\ComfyUI\comfyui_env\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
TypeError: _get_model_file() got an unexpected keyword argument 'resume_download'

**Comment by doganerr** [comment]
same error.

**Comment by KimMatt** [comment]
Yeah got this too. Is it a versioning issue?

To temporarily fix you can go to: `ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CharacterGen\Stage_2D\tuneavideo\models\unet_mv2d_condition.py`
and 
`/ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\CharacterGen\Stage_2D\tuneavideo\models\unet_mv2d_condition.py`

and in any calls to _get_model_file() remove the 'resume_download' argument

**Comment by RainEmy** [comment]
这是缺少模型的原因，缺少哪个模型就在作者项目主页里找到对应的模型下载链接

**Comment by drake7707** [comment]
Broken in diffusers==0.30.2 due to https://github.com/huggingface/diffusers/commit/e02ec27e51751a28a4fa1e0d95537f824d523bbe, use diffusers==0.30.0 in requirements.txt

**Comment by drake7707** [comment]
> Yeah got this too. Is it a versioning issue?
> 

Yes, pip install diffusers==0.29.0 to prevent errors in _get_model_file

**Comment by DenisKochetov** [comment]
https://github.com/MrForExample/ComfyUI-3D-Pack/pull/520
fixed, thank you
