### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links: 'hipconfig'

### ISSUE THREAD

**Issue by v4r4rth** [MrForExample/ComfyUI-3D-Pack#31]
Getting this error:

```
(comfyui) root@a100-instance-ajna:~/ComfyUI/custom_nodes/ComfyUI-3D-Pack# pip install ./diff-gaussian-rasterization
Processing ./diff-gaussian-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/ComfyUI/custom_nodes/ComfyUI-3D-Pack/diff-gaussian-rasterization/setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "/root/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 22, in <module>
          from .hipify import hipify_python
        File "/root/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/root/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/anaconda3/envs/comfyui/lib/python3.11/subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/anaconda3/envs/comfyui/lib/python3.11/subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/anaconda3/envs/comfyui/lib/python3.11/subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/root/anaconda3/envs/comfyui/lib/python3.11/subprocess.py", line 1950, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      OSError: [Errno 40] Too many levels of symbolic links: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I haven't encountered any OSError or Symbolic link error before, fairly good at managing cuda versions so please do suggest what I can do to get the updated pack working?

**Comment by MrForExample** [comment]
Hi friend, have you tried [this solution](https://stackoverflow.com/questions/66410156/docker-overlay2-error-walking-file-system-oserror-errno-40-too-many-levels-o)

**Comment by DenisKochetov** [comment]
try to install the last version
