### ISSUE TITLE
No such file or directory: 'D:\\...ComfyUI-3D-Pack\\Configs/system.conf'

### ISSUE THREAD

**Issue by DuckersMcQuack** [MrForExample/ComfyUI-3D-Pack#310]
Installed the latest 3d pack manually, and comfy can't find it. 
```
Traceback (most recent call last):
  File "D:\Stablediff\Comfyuimanual\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\__init__.py", line 36, in <module>
    f = open(conf_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Stablediff\\Comfyuimanual\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\Configs/system.conf'

```

Then attempted through comfyui manager, and this is the bootup error from that version.

```
#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['D:\\Stablediff\\Comfyuimanual\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'PyGithub']

## Execute install/(de)activation script for 'D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack'

## ComfyUI-Manager: EXECUTE => ['D:\\Stablediff\\Comfyuimanual\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'open_clip_torch']

## Execute install/(de)activation script for 'D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack'

## ComfyUI-Manager: EXECUTE => ['D:\\Stablediff\\Comfyuimanual\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'pytorch_msssim']

## Execute install/(de)activation script for 'D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack'

## ComfyUI-Manager: EXECUTE => ['D:\\Stablediff\\Comfyuimanual\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'PyMCubes']

## Execute install/(de)activation script for 'D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack'

## ComfyUI-Manager: EXECUTE => ['D:\\Stablediff\\Comfyuimanual\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack'
[!] Traceback (most recent call last):
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
[!]     from build_utils import (
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
[!]     CUDA_VERSION = get_cuda_version()
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 43, in get_cuda_version
[!]     result = subprocess.run(["nvcc", "--version"], text=True, capture_output=True)
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
[!]     with Popen(*popenargs, **kwargs) as process:
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
[!]     self._execute_child(args, executable, preexec_fn, close_fds,
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
[!]     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
[!] FileNotFoundError: [WinError 2] The system cannot find the file specified
[!] Traceback (most recent call last):
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
[!]     from build_utils import (
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
[!]     CUDA_VERSION = get_cuda_version()
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 43, in get_cuda_version
[!]     result = subprocess.run(["nvcc", "--version"], text=True, capture_output=True)
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
[!]     with Popen(*popenargs, **kwargs) as process:
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
[!]     self._execute_child(args, executable, preexec_fn, close_fds,
[!]   File "C:\Users\DuckersMcQuack\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
[!]     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
[!] FileNotFoundError: [WinError 2] The system cannot find the file specified
[!]
[!] During handling of the above exception, another exception occurred:
[!]
[!] Traceback (most recent call last):
[!]   File "D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 84, in <module>
[!]     cstr("Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.").error.print()
[!] NameError: name 'cstr' is not defined. Did you mean: 'str'?
install/(de)activation script failed: D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack

[ComfyUI-Manager] Startup script completed.
#######################################################################
```

**Comment by MrForExample** [comment]
The error file is in: `D:\Stablediff\Comfyuimanual\ComfyUI\custom_nodes\ComfyUI-3D-Pack-main\__init__.py`
Yet the path it trying to find is: `D:\\Stablediff\\Comfyuimanual\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\Configs/system.conf'`

rename ComfyUI-3D-Pack-main to ComfyUI-3D-Pack should solve the issue

**Comment by DuckersMcQuack** [comment]
Oh, that it should indeed. 

So, the last error didn't appear today with the manager installed one, but i got a module missing being kiui, which i installed manually, so, might need it in it's initial install script.

As well as nvdiffrast was missing. But it couldn't install.
```
pip install nvdiffrast
ERROR: Could not find a version that satisfies the requirement nvdiffrast (from versions: none)
ERROR: No matching distribution found for nvdiffrast
```

**Comment by CamelliasW** [comment]
`git clone https://github.com/NVlabs/nvdiffrast.git
cd nvdiffrast/
pip install .
`

**Comment by staltux** [comment]
here on my end i have similar problem, the script try to load ComfyUI-3D-Pack but the folder is created with lowercase, linux is case sensitive, renaming the folder fixes it
