### ISSUE TITLE
Installation Issues with ComfyUI manager (imported fail)

### ISSUE THREAD

**Issue by 0mil** [MrForExample/ComfyUI-3D-Pack#314]
Hello,

This custom_node is surprisingly awesome!
However, it's extremely difficult to install successfully.

I have tried to install this custom_node using various configurations, including Ubuntu LTS, and Windows 10 with CUDA version 11.8 and 12.1. Currently, I am following the guide from [this video](https://www.youtube.com/watch?v=RjuoLMCpvbI), but I have also encountered the same failure with the installation of PyTorch3D.

Therefore, I sincerely request assistance: **what is the best way to install this custom node using ComfyUI Manager or any other installation steps?** Please provide the exact and specific requirements, including the supported OS, CUDA version, and Torch library version. I would like to try installing it again with the correct specifications. Thank you. 😂😂😂

```bash
C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
DEPRECATION: Loading egg at c:\users\jh.park\downloads\comfyui_3d\comfyui_windows_portable\python_embeded\lib\site-packages\nvdiffrast-0.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
[DONE] Security scan
[ComfyUI-Manager] Logging failed: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다: 'comfyui.log' -> 'comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-23 14:55:03.687033
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.7 seconds: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10239 MB, total RAM 16326 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 57, in <module>
    from TriplaneGaussian.triplane_gaussian_transformers import TGS
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\triplane_gaussian_transformers.py", line 6, in <module>
    from TriplaneGaussian.models.image_feature import ImageFeature
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\models\image_feature.py", line 7, in <module>
    from ..utils.ops import compute_distance_transform
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py", line 8, in <module>
    from pytorch3d import io
ImportError: cannot import name 'io' from 'pytorch3d' (unknown location)

Cannot import C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: cannot import name 'io' from 'pytorch3d' (unknown location)
### Loading: ComfyUI-Manager (V2.51)
### ComfyUI Revision: 2360 [4ca9b9cc] *DETACHED | Released on '2024-07-12'

Import times for custom nodes:
   0.0 seconds: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.5 seconds: C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.3 seconds (IMPORT FAILED): C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

Traceback (most recent call last):
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\main.py", line 258, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\main.py", line 153, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\ComfyUI\server.py", line 669, in start
    await site.start()
  File "C:\Users\jh.park\Downloads\ComfyUI_3D\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1536, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): 각 소켓 주소(프로토콜/네트워크 주소/포트)는 하나만 사용할 수 있습니다
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

**Comment by jakechai** [comment]
It looks like your pytorch3d is not installed properly. 
Here is the torch2.3.0 pytorch3d wheel in `...\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Wheels\_Wheels_win_py311_cu121`

Try reinstall pytorch3d: `...\python.exe -m pip install "...\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Wheels\_Wheels_win_py311_cu121\pytorch3d-0.7.7-cp311-cp311-win_amd64.whl"`

I will update the video's description for the new update of torch2.4.0.

**Comment by AN3Orik** [comment]
New ComfyUI has torch2.4.1 installed by default and it's just impossible to install 3D-Pack to portable.

**Comment by jakechai** [comment]
> New ComfyUI has torch2.4.1 installed by default and it's just impossible to install 3D-Pack to portable.

Install torch2.4.0 first

**Comment by MrForExample** [comment]
@AN3Orik If you run the: `"Your comfyUI python.exe" install.py` it should automatically download everything in the correct version

**Comment by MrForExample** [comment]
@0mil ComfyUI-Manager should work for most cases, both torch2.3 and torch2.4 should work
But in your case, you can try those two steps separately under ComfyUI-3D-Pack folder and see what other errors you got:
1. `"Your comfyUI python.exe" -s -m pip -r requirements.txt`
2. `"Your comfyUI python.exe" install.py`

**Comment by 0mil** [comment]
@MrForExample 
It completley works. Thank you for your answering and awesome works. 👍👍👍

**Comment by GPU-server** [comment]
> @0mil ComfyUI-Manager should work for most cases, both torch2.3 and torch2.4 should work But in your case, you can try those two steps separately under ComfyUI-3D-Pack folder and see what other errors you got:
> 
> 1. `"Your comfyUI python.exe" -s -m pip -r requirements.txt`
> 2. `"Your comfyUI python.exe" install.py`

Hello @MrForExample , do you mean we must go to comfyui 3D pack folder under CUSTOM NODES, then open terminal and write this? 
"My_ComfyUI_path\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip -r requirements.txt"
??
Please confirm

**Comment by 0mil** [comment]
Yeah, you almost got it!
But, actually, there are some mistyped.
You have to execute the below command.
```bash
#firstly
MyComfyUiPath\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack>"D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe" -s -m pip install -r requirements.txt

#secondly
MyComfyUiPath\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack>"D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe" install.py
```
