### ISSUE TITLE
Can never get it to work

### ISSUE THREAD

**Issue by PJR1987** [MrForExample/ComfyUI-3D-Pack#323]
I have been at the forefront of all things generative AI for over 2 years and this is the only thing I have ever struggled with.
I even DOWNGRADED Torch to 2.3 to try and get it running, only for Comfy3D to force upgrade back to 2.4.

Nothing I have tried, and I have tried every issue ticket and every youtube video going. No matter what I do it always fails and always shows as failing in the node manager.

It also tells me absolutely nothing of use or help as to why it never works. I have even fresh installed a new PC which I think is now screwed because of all the things I've tried doing to get this working and I will need to format it again.

This is the latest error I have got, but not something I got any of the other 10 times I tried to get this running:

Traceback (most recent call last):
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 57, in <module>
    from TriplaneGaussian.triplane_gaussian_transformers import TGS
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\triplane_gaussian_transformers.py", line 6, in <module>
    from TriplaneGaussian.models.image_feature import ImageFeature
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\models\image_feature.py", line 7, in <module>
    from ..utils.ops import compute_distance_transform
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py", line 8, in <module>
    from pytorch3d import io
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\io\__init__.py", line 10, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "C:\Users\PJ\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pytorch3d\io\obj_io.py", line 19, in <module>
    from iopath.common.file_io import PathManager
ModuleNotFoundError: No module named 'iopath'

**Comment by tcarneyjohnson** [comment]
You should probably ask for a refund.

**Comment by PJR1987** [comment]
> You should probably ask for a refund.

Oh, there are trolls and shitposters on GitHub too.

**Comment by tcarneyjohnson** [comment]
> > You should probably ask for a refund.
> 
> Oh, there are trolls and shitposters on GitHub too.

My point is that there is ONE person working on this project. You have paid literally nothing for this and yet you have the audacity to post such a rude, whiney comment. Are you really so deluded that you don't realize how spoiled and entitled you sound?

I'm no expert, but I can see from the error message you posted that you've made a pretty basic mistake and forgotten a step. I'm not going to help you because your attitude sucks.

**Comment by PJR1987** [comment]
I would pay for it, if it worked. This is why github exists, to get free feedback for users to get something working properly so you can later make money from it. I can assure you I have not forgotten any steps.

Keep trolling, if it is effective use of your life I am happy for you.

**Comment by tcarneyjohnson** [comment]
> I would pay for it, if it worked. This is why github exists, to get free feedback for users to get something working properly so you can later make money from it. I can assure you I have not forgotten any steps.
> 
> Keep trolling, if it is effective use of your life I am happy for you.

I know your feedback is extremely valuable, especially given that you are "at the forefront of all things generative AI", but I sincerely doubt that the creator of this project has any plans to monetize it. This is a custom node set for an obscure, already open source project we are talking about.

While feedback is important, Github exists primarily as a means of collaboration for programmers, in particular for community driven open source software. Collaboration depends on a positive, respectful, and helpful attitude -  all things you seem to lack.

I'm not going to bother answering any more messages from you, as you've already made yourself look quite foolish and it would be trolling at that point.

Good luck navigating through your life with your out of control sense of self importance!

**Comment by PJR1987** [comment]
You literally can't even get it running yourself, and waste your life shitposting and trolling here as if it's easy to get running.

What an absolute clown.

**Comment by tcarneyjohnson** [comment]
@PJR1987 Deleting my comments from yesterday. People get frustrated and have bad days, myself definitely included.

Hope you figure this out, have a good one.

**Comment by clyce** [comment]
run `pip install iopath` in your comfyui python env

**Comment by JimWang151** [comment]
pytorch3d have not been installed normallly.

There are 3 stage of 3D-Pack installation.
1.setup stage of install.py,we must process all the conflicts between the specified package and exsits env. you use now.As my experiences, xformers must be the highest level for it.
2.pytorch and  cuda version,as my progress of installation,version 2.4 is necessary for the current version.So my suggestion is build an individual environment for 3D-Pack base on conda.
3.Visual Studio Tool and Windows KIT.include : x64 Version of mvcc,cl.exe path specified in the system env variables.The two tools are the basis to use ninja.By the progress of Ninja using,maybe you must handle the ninja installation problem or LONG PATH Setting. After the two  tools been settled,you also need to place all the obj,lib,or .h file contain in the INCLUDE environment variables.Remember,the lib files needed must contained in the libpath variables.

According to route of 3 steps above,this package can be installed easier and easier.

**Comment by tcarneyjohnson** [comment]
@PJR1987 Hopefully you've gotten this working by now, but if not:

I was able to get this working again after a period of having it broken by using Chat GPT to analyze the error. (I am not a programmer, and this was the easiest way to get specific step by step instructions for my setup) In my case I had more errors listed that you seem to have, and you may only need to update your local ComfyUI Python install to take care of the missing "iopath" module.

Start with your ComfyUI fully up to date.

Copy/paste the error into the Chat GPT text field and specify that you want it to search for instructions to fix the problem for the ComfyUI 3D Pack online. It should spit out instructions for how to install/uninstall/reinstall components for your local ComfyUI build, including the local "iopath" module.

If it says you have mismatched versions of pytorch and torchaudio, etc. you'll need correct the instructions to replace the version/address for pytorch with "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121" (or whatever the appropriate version is for your machine).

Hope all is well.

**Comment by xXZOKOXx** [comment]
Followed every instructions of Chatgpt and still can't get it running on a fresh install of comfyUI portable...

PyTorch version: 2.4.0+cu118
CUDA: 11.8
Torchaudio version: 2.4.0+cu118
xFormers version: 0.0.27.post2+cu118
iopath version: 0.1.10
PyTorch3D version: 0.7.8

Microsoft Visual C++ Redistributable installed and Visual Studio 2022

**Comment by PJR1987** [comment]
> pytorch3d have not been installed normallly.
> 
> There are 3 stage of 3D-Pack installation. 1.setup stage of install.py,we must process all the conflicts between the specified package and exsits env. you use now.As my experiences, xformers must be the highest level for it. 2.pytorch and cuda version,as my progress of installation,version 2.4 is necessary for the current version.So my suggestion is build an individual environment for 3D-Pack base on conda. 3.Visual Studio Tool and Windows KIT.include : x64 Version of mvcc,cl.exe path specified in the system env variables.The two tools are the basis to use ninja.By the progress of Ninja using,maybe you must handle the ninja installation problem or LONG PATH Setting. After the two tools been settled,you also need to place all the obj,lib,or .h file contain in the INCLUDE environment variables.Remember,the lib files needed must contained in the libpath variables.
> 
> According to route of 3 steps above,this package can be installed easier and easier.

Thanks for trying to help but I still cannot get this to run at all, unlike 100% of everything else I have ever tried...

Still get iopath error when iopath is installed.
Installing Comfy3D gives a nodes_audio.py error, what the hell has audio got to do with 3d?

**Comment by MrForExample** [comment]
Hi all, I just updated the [pre-builds](https://github.com/MrForExample/Comfy3D_Pre_Builds) for 
`Windows; Python 3.10, 3.11, 3.12; pytorch 2.5.0, torchvision 0.20.0, xformer 0.28.0 post2`
Hope you had a good weekend :)

**Comment by PJR1987** [comment]
> Hi all, I just updated the [pre-builds](https://github.com/MrForExample/Comfy3D_Pre_Builds) for `Windows; Python 3.10, 3.11, 3.12; pytorch 2.5.0, torchvision 0.20.0, xformer 0.28.0 post2` Hope you had a good weekend :)

I appreaciate your work, I had spent another 6h or so before you made this post still failing to get it to work no matter what I tried.

Does it work regardless of what version of CUDA you have installed, or only for 12.1? I tried downgrading everything to the CUDA, Torch, etc. you specified and still couldn't get it working. Still numerous errors which gave no helpful information. I will try again on my laptop to see if I get a different result for any reason.

**Comment by DenisKochetov** [comment]
@PJR1987 try new version with wheels for cuda 12.8
