### ISSUE TITLE
The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 600, 600, 3] at index 1

### ISSUE THREAD

**Issue by rob-ack** [MrForExample/ComfyUI-3D-Pack#328]
# ComfyUI Error Report
## Error Details
- **Node Type:** [Comfy3D] Era3D MVDiffusion Model
- **Exception Type:** IndexError
- **Exception Message:** The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 600, 600, 3] at index 1
## Stack Trace
```
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 2551, in run_model
    single_image = torch_imgs_to_pils(reference_image, reference_mask)[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\image_utils.py", line 31, in torch_imgs_to_pils
    images[inv_mask_index] = 0.
    ~~~~~~^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-90-g2c641e6
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589803520
  - **VRAM Free:** 3533158838
  - **Torch VRAM Total:** 4026531840
  - **Torch VRAM Free:** 18958774

## Logs
```
2024-10-06 18:08:41,658 - root - INFO - Total VRAM 8192 MB, total RAM 65375 MB
2024-10-06 18:08:41,658 - root - INFO - pytorch version: 2.4.0+cu121
2024-10-06 18:08:42,459 - root - INFO - xformers version: 0.0.27.post2
2024-10-06 18:08:42,465 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-06 18:08:42,466 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
2024-10-06 18:08:42,596 - root - INFO - Using xformers cross attention
2024-10-06 18:08:43,495 - root - INFO - [Prompt Server] web root: C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-06 18:08:43,969 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\__init__.py", line 42, in <module>
    _check_cuda_version()
  File "C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\utils.py", line 175, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 12.4. Please install the TorchAudio version that matches your PyTorch version.

2024-10-06 18:08:43,970 - root - WARNING - Cannot import C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_audio.py module for custom nodes: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 12.1 whereas TorchAudio has CUDA version 12.4. Please install the TorchAudio version that matches your PyTorch version.
2024-10-06 18:08:45,087 - py.warnings - WARNING - C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

2024-10-06 18:08:45,087 - py.warnings - WARNING - C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

2024-10-06 18:08:45,118 - py.warnings - WARNING - C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:38: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)

2024-10-06 18:08:45,118 - py.warnings - WARNING - C:\Users\rober\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:44: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":28,"last_link_id":48,"nodes":[{"id":25,"type":"[Comfy3D] InstantMesh Reconstruction Model","pos":{"0":1627.0196533203125,"1":108.94257354736328},"size":{"0":315,"1":122},"flags":{},"order":7,"mode":0,"inputs":[{"name":"lrm_model","type":"LRM_MODEL","link":43},{"name":"multiview_images","type":"IMAGE","link":48},{"name":"orbit_camera_poses","type":"ORBIT_CAMPOSES","link":47}],"outputs":[{"name":"mesh","type":"MESH","links":[46],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] InstantMesh Reconstruction Model"},"widgets_values":[30,1024]},{"id":28,"type":"[Comfy3D] Switch Mesh Axis","pos":{"0":1988.0196533203125,"1":107.94257354736328},"size":{"0":315,"1":154},"flags":{},"order":8,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":46}],"outputs":[{"name":"switched_mesh","type":"MESH","links":[44],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] Switch Mesh Axis"},"widgets_values":["+y","+z","+x",false,1]},{"id":24,"type":"[Comfy3D] Load InstantMesh Reconstruction Model","pos":{"0":1248,"1":109},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"lrm_model","type":"LRM_MODEL","links":[43],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] Load InstantMesh Reconstruction Model"},"widgets_values":["instant_mesh_large.ckpt"]},{"id":22,"type":"[Comfy3D] Era3D MVDiffusion Model","pos":{"0":1118,"1":232},"size":{"0":418.1999816894531,"1":242},"flags":{},"order":4,"mode":0,"inputs":[{"name":"era3d_pipe","type":"DIFFUSERS_PIPE","link":38},{"name":"reference_image","type":"IMAGE","link":40},{"name":"reference_mask","type":"MASK","link":39}],"outputs":[{"name":"multiviews","type":"IMAGE","links":[41,48],"slot_index":0,"shape":3},{"name":"multiview_normals","type":"IMAGE","links":[42],"slot_index":1,"shape":3},{"name":"orbit_camposes","type":"ORBIT_CAMPOSES","links":[47],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] Era3D MVDiffusion Model"},"widgets_values":[420,600,"fixed",3,40,1,4]},{"id":7,"type":"InvertMask","pos":{"0":878,"1":417},"size":{"0":140,"1":26},"flags":{},"order":3,"mode":0,"inputs":[{"name":"mask","type":"MASK","link":5}],"outputs":[{"name":"MASK","type":"MASK","links":[39],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"InvertMask"},"widgets_values":[]},{"id":27,"type":"[Comfy3D] Preview 3DMesh","pos":{"0":2702,"1":109},"size":[600,500],"flags":{},"order":10,"mode":0,"inputs":[{"name":"mesh_file_path","type":"STRING","link":45,"widget":{"name":"mesh_file_path"}}],"outputs":[],"properties":{"Node name for S&R":"[Comfy3D] Preview 3DMesh"},"widgets_values":["",null]},{"id":11,"type":"PreviewImage","pos":{"0":1627,"1":354},"size":{"0":1043.55126953125,"1":246},"flags":{},"order":5,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":41}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":23,"type":"PreviewImage","pos":{"0":1629,"1":676},"size":{"0":1043.55126953125,"1":246},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":42}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":26,"type":"[Comfy3D] Save 3D Mesh","pos":{"0":2354.01953125,"1":107.94257354736328},"size":{"0":315,"1":58},"flags":{},"order":9,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":44}],"outputs":[{"name":"save_path","type":"STRING","links":[45],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] Save 3D Mesh"},"widgets_values":["InstantMesh_test\\Priest_Cat.glb"]},{"id":6,"type":"LoadImage","pos":{"0":423,"1":424},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[40],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":[5],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["mechfront.jpg","image"]},{"id":1,"type":"[Comfy3D] Load Diffusers Pipeline","pos":{"0":417,"1":195},"size":{"0":383.9324645996094,"1":154},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"pipe","type":"DIFFUSERS_PIPE","links":[38],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"[Comfy3D] Load Diffusers Pipeline"},"widgets_values":["Era3DPipeline","pengHTYX/MacLab-Era3D-512-6view","",false,""]}],"links":[[5,6,1,7,0,"MASK"],[38,1,0,22,0,"DIFFUSERS_PIPE"],[39,7,0,22,2,"MASK"],[40,6,0,22,1,"IMAGE"],[41,22,0,11,0,"IMAGE"],[42,22,1,23,0,"IMAGE"],[43,24,0,25,0,"LRM_MODEL"],[44,28,0,26,0,"MESH"],[45,26,0,27,0,"STRING"],[46,25,0,28,0,"MESH"],[47,22,2,25,2,"ORBIT_CAMPOSES"],[48,22,0,25,1,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[-308.5984912517147,306.89187500460093]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by rob-ack** [comment]
Pls help me out how to get rid of this!

**Comment by rob-ack** [comment]
Is this the reason? https://github.com/MrForExample/ComfyUI-3D-Pack/issues/309

**Comment by jakechai** [comment]
Shape issue: the mask's resolution value should be the multiple of 64
TorchAudio issue: torchaudio cu121, not cu124

**Comment by rob-ack** [comment]
According to Copilot:

> ## Copilot
> It seems like the error you're encountering is related to the torch_imgs_to_pils function in the ComfyUI 3D Pack. This error typically occurs when the image doesn't have a transparent background, causing the mask to fail to load properly.
> Here are a few steps you can try to fix this issue:
> - Check the Image Background: Ensure that the image you're using has a transparent background. If not, you might need to edit the image to add transparency.
> - Update ComfyUI and Dependencies: Make sure you have the latest version of ComfyUI and its dependencies. Sometimes, updating to the latest version can resolve compatibility issues.
> - Modify the Code: If you're comfortable with coding, you can modify the torch_imgs_to_pils function to handle images without transparent backgrounds. For example, you can add a check to ensure the mask is valid before applying it.
> - Seek Community Help: If the above steps don't work, consider reaching out to the ComfyUI community on GitHub or other forums. They might have encountered similar issues and could offer solutions.
> If you need more detailed guidance on any of these steps, feel free to ask!

Then i made a simple test using a 'ImageColorToMask' node.

![image](https://github.com/user-attachments/assets/160176c9-ff69-4ce1-886e-562a475fc3d2)

Now i got it to run on the Era3D_to_InstantMesh.json workload.
