### ISSUE TITLE
Error while perform example workflow of CharacterGen:CharacterGen_InstantMesh.json

### ISSUE THREAD

**Issue by JimWang151** [MrForExample/ComfyUI-3D-Pack#331]
The multi-view can be run smoothly as below:
![image](https://github.com/user-attachments/assets/fc754968-4b94-48b5-a3ba-10c6373a53d4)

But when runing the **InstantMesh Reconstruction Model** node ,the error message like this:

[Comfy3D] [Load_CharacterGen_MVDiffusion_Model] loaded model ckpt from D:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Checkpoints\CharacterGen
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [04:30<00:00,  6.77s/it]
2024-10-07 15:56:18.8988851 [E:onnxruntime:Default, provider_bridge_ort.cc:1978 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:490 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-10-07 15:56:21.2322045 [E:onnxruntime:Default, provider_bridge_ort.cc:1978 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:490 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-10-07 15:56:22.8107869 [E:onnxruntime:Default, provider_bridge_ort.cc:1978 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:490 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-10-07 15:56:24.3039914 [E:onnxruntime:Default, provider_bridge_ort.cc:1978 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:490 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
!!! Exception during processing !!! instance mode - pos must have shape [>0, >0, 4]
Exception raised from rasterize_fwd_cuda at D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\torch_rasterize.cpp:62 (most recent call first):
00007FFF41CA462900007FFF41CA4580 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFF41CA416A00007FFF41CA4110 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFF67341B5500007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730EE1300007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730DFE200007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF673278FF00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730506F00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF67333E4E00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF647882BE00007FFF64788060 python311.dll!PyObject_MakeTpCall [<unknown file> @ <unknown line number>]
00007FFF6478BDDF00007FFF6478BB50 python311.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF6478D42300007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF6483507300007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFE42C5134100007FFE42C3DE40 torch_python.dll!THPPointer<_frame>::THPPointer<_frame> [<unknown file> @ <unknown line number>]
00007FFF647B75F500007FFF647B7540 python311.dll!PyArg_Parse_SizeT [<unknown file> @ <unknown line number>]
00007FFF648350C400007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFF64834D4000007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF64834C6A00007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF647D5C2500007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF64834C6A00007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF647D5AA500007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF64834CF300007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF64834CF300007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF647D5C7F00007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF6483507300007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFF647F2AA000007FFF647F26EC python311.dll!PyInterpreterState_Delete [<unknown file> @ <unknown line number>]
00007FFF647F2A0600007FFF647F26EC python311.dll!PyInterpreterState_Delete [<unknown file> @ <unknown line number>]
00007FFFD002933300007FFFD0029290 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
00007FFFD013257D00007FFFD0132560 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFFD244AF2800007FFFD244AF00 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

Traceback (most recent call last):
  File "D:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 2490, in run_LRM
    mesh_out = lrm_model.extract_mesh(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\InstantMesh\models\lrm.py", line 198, in extract_mesh
    uvs, mesh_tex_idx, gb_pos, tex_hard_mask = xatlas_uvmap(
                                               ^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\InstantMesh\utils\mesh_util.py", line 176, in xatlas_uvmap
    rast, _ = dr.rasterize(ctx, uv_clip4, mesh_tex_idx.int(), (resolution, resolution))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\autograd\function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 248, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: instance mode - pos must have shape [>0, >0, 4]
Exception raised from rasterize_fwd_cuda at D:\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\torch_rasterize.cpp:62 (most recent call first):
00007FFF41CA462900007FFF41CA4580 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFF41CA416A00007FFF41CA4110 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFF67341B5500007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730EE1300007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730DFE200007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF673278FF00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF6730506F00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF67333E4E00007FFF673044D0 nvdiffrast_plugin.pyd!PyInit_nvdiffrast_plugin [<unknown file> @ <unknown line number>]
00007FFF647882BE00007FFF64788060 python311.dll!PyObject_MakeTpCall [<unknown file> @ <unknown line number>]
00007FFF6478BDDF00007FFF6478BB50 python311.dll!PyObject_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF6478D42300007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF6483507300007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFE42C5134100007FFE42C3DE40 torch_python.dll!THPPointer<_frame>::THPPointer<_frame> [<unknown file> @ <unknown line number>]
00007FFF647B75F500007FFF647B7540 python311.dll!PyArg_Parse_SizeT [<unknown file> @ <unknown line number>]
00007FFF648350C400007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFF64834D4000007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF64834C6A00007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF647D5C2500007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF64834C6A00007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF647D5AA500007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF64834CF300007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF64834CF300007FFF648348EC python311.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF64791F7F00007FFF6478CC20 python311.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF6478AE6400007FFF6478ACC0 python311.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF647D5C7F00007FFF647D3DC4 python311.dll!PyIter_Send [<unknown file> @ <unknown line number>]
00007FFF6483507300007FFF64835018 python311.dll!PyObject_Call [<unknown file> @ <unknown line number>]
00007FFF647F2AA000007FFF647F26EC python311.dll!PyInterpreterState_Delete [<unknown file> @ <unknown line number>]
00007FFF647F2A0600007FFF647F26EC python311.dll!PyInterpreterState_Delete [<unknown file> @ <unknown line number>]
00007FFFD002933300007FFFD0029290 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
00007FFFD013257D00007FFFD0132560 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFFD244AF2800007FFFD244AF00 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

Prompt executed in 429.09 seconds

![image](https://github.com/user-attachments/assets/a079e226-70d0-47f4-aff8-bc28e7344bb7)

Thanks for your care.

**Comment by MrForExample** [comment]
Hi @JimWang151 
I just checked it, and I can run the workflow without error.
Can I ask what kind GPU you are using, also I'm not sure why the error message mentioned **onnxruntime**.
Moreover, please check if you installed [Visual Studio Build Tools 2022/2019](https://visualstudio.microsoft.com/downloads/?q=build+tools) with Workloads: Desktop development with C++ (There are a few JIT torch cpp extension that builds in runtime)
