### ISSUE TITLE
Spent 4H (actually more) trying to install this! I tried 3 methods and all FAILED! There is something I must be doing wrong. Please Check and tell me

### ISSUE THREAD

**Issue by GPU-server** [MrForExample/ComfyUI-3D-Pack#333]
Hello
**_First Method I tried_**:
 using ComfyUI manager. The extension showed as "**IMPORT FAILED**". 
Trying to FIX it, would not work unfortunately.

_**2nd method:**_
Tried to use the scripts located inside the custom node, requirements.txt and install.py.
I don't recall if I treid this on a fresh git cloned repo or it was on a custom node installed from the manager (would have that mattered?)

> D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack>"D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe" -s -m pip install -r requirements.txt

100% of them were already "satisfied" aka installed, because I had probably already installed it from manager, however I then used this:

> D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack>"D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe" install.py

Got this error : **NameError: name 'cstr' is not defined. Did you mean: 'str'?**
Full error:

> Traceback (most recent call last):
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
>     from build_utils import (
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
>     CUDA_VERSION = get_cuda_version()
>                    ^^^^^^^^^^^^^^^^^^
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 49, in get_cuda_version
>     raise RuntimeError(f"Please install/reinstall CUDA tookit with any of the following supported version: {build_config.supported_cuda_versions}")
> RuntimeError: Please install/reinstall CUDA tookit with any of the following supported version: ['12.1', '11.8']
> Traceback (most recent call last):
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
>     from build_utils import (
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
>     CUDA_VERSION = get_cuda_version()
>                    ^^^^^^^^^^^^^^^^^^
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 49, in get_cuda_version
>     raise RuntimeError(f"Please install/reinstall CUDA tookit with any of the following supported version: {build_config.supported_cuda_versions}")
> RuntimeError: Please install/reinstall CUDA tookit with any of the following supported version: ['12.1', '11.8']
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 84, in <module>
>     cstr("Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.").error.print()
>     ^^^^
> NameError: name 'cstr' is not defined. Did you mean: 'str'?

**_3rd method:_**
moving on to another method, I tried to read and understand the readme instructions and I see WHEEL pre builds mentioned, I did some research and understood that I had to download the one I need from the list of pre builds.
I had: 
- Python 3.11
- Torch 2.4.1 (comes with latest comfyui)
- Cuda 1.2.1
I performed an uninstall, and tried to obtain 2.4.0, because there were no 2.4.1 Pre builds available, **am I wrong?**

I did the following to install each wheel:
`MyPathToMbedded\python.exe -m pip install --force-reinstall "pathToWheelFile1"`
I encountered some ERRORS during these installations but they were "successful" supposeldy. For example:

> numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.1.2 which is incompatible

.
After installing them all, the logs showed errors related to:
Torch scatter then ninja.
I installed both, and I also fixed numpy version:
```
D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded>python.exe -m pip install torch-scatter -f https://data.pyg.org/whl/torch-2.4.0+cu121.html
python.exe -m pip install numpy==2.0
python.exe -s -m pip install --force-reinstall ninja
```
And I even fixed an error related to: 
**AttributeError: np.Inf was removed in the NumPy 2.0 release. Use np.inf instead.**
inside : ..site-packages\gpytoolbox\reach_for_the_arcs.py

I am still having an error related to ninja despite installing it:

> D:\NewInstalls\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: ... include : 'Python.h' : No such file or directory
> ninja: build stopped: subcommand failed.

What can I do now?
Thanks.
Also tell me if my method of using the wheels/pre build. was correct?
Or if I missed any other installation method. 
Please let forget this hell haha.
Thanks

Edit: In the end I tried to run the requirements.txt again, and everything was set except numpy who suprisingly went back to 1.26.4, but I am still getting the ninja error.

Edit2: one last thing, I tried to expandmy research and figured it could be missing cuda runtime (https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/198)
Tried installing both 1.8 and latest 2.+, neither changed anything for comfy 3D PACK. Import still "failed".

I tried one last time "FIX" with comfy manager and it showed me this :o 
![image](https://github.com/user-attachments/assets/0b8957cb-6c6a-4c73-898f-acf770d46572)
The logs showed:

**ERROR: To use this action, a security_level of `middle or below` is required. Please contact the administrator.
Reference: https://github.com/ltdrdata/ComfyUI-Manager#security-policy**

Please help.

**Comment by GPU-server** [comment]
Final comment on this:
The method I tried was wrong, I installed the extension from  manager, then tried to solve the issues by installing the wheel from the pre build files one by one.
The better method was the one in the readme:
- Either git clone the repo THEN try to install.py (while pointing at the python.exe of the embedded python for comfy), while making sure you have cuda toolkit (the right version 12.1 with pytorch 2.4.0 etc)
- or follwo the complicated but seemlingly worth it method here: https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Pre_Builds/README.md#build-required-packages-semi-automatically
- you can also opt in for a pre installed one from: https://github.com/YanWenKun/ComfyUI-Windows-Portable
dont know if it is secure, probably is. But I prefer to have mmy own installation.
- security level in comfy manager also got in the way.
it seems there are many libraires that conflit with each other, maybe the best thing to do is to use what they docker.
Other people even installed comfy manually with conda in a new env, instead of using the portable version.
Good luck
