### ISSUE TITLE
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host

### ISSUE THREAD

**Issue by gioxyer** [MrForExample/ComfyUI-3D-Pack#365]
FETCH DATA from: https://github.com/ltdrdata/ComfyUI-Manager/raw/main/custom-node-list.json [DONE]
Install custom node 'ComfyUI-3D-Pack'
Install: ['https://github.com/MrForExample/ComfyUI-3D-Pack']
Download: git clone 'https://github.com/MrForExample/ComfyUI-3D-Pack'
[!]
100%|██████████| 707.0/707.0 [00:00<00:00, 892.52it/s]
100%|██████████| 707.0/707.0 [00:00<00:00, 892.52it/s]
100%|██████████| 381.0/381.0 [00:00<00:00, 449.98it/s]
100%|██████████| 381.0/381.0 [00:00<00:00, 449.98it/s]
100%|██████████| 3453.0/3453.0 [10:34<00:00,  5.44it/s]
100%|██████████| 3453.0/3453.0 [10:34<00:00,  5.44it/s]
100%|██████████| 1140.0/1140.0 [10:34<00:00,  1.80it/s]
 Cmd('git') failed due to: exit code(128)
100%|██████████| 1140.0/1140.0 [10:34<00:00,  1.80it/s]
100%|██████████| 1140.0/1140.0 [10:37<00:00,  1.79it/s]
  cmdline: git clone -v --recursive --progress -- https://github.com/MrForExample/ComfyUI-3D-Pack C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Connection in progress forcibly aborted by remote host

![immagine](https://github.com/user-attachments/assets/57eecf8c-f0a9-46b4-9403-ad82e4fd48bf)

**Comment by thoi86** [comment]
Same issue!

**Comment by bendreality** [comment]
Found the problem, but no solution...

I tried to clone the git repo directly and got this error:

```
C:\Users\nhb\stability_matrix\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack>git clone https://github.com/MrForExample/ComfyUI-3D-Pack.git .
Cloning into '.'...
remote: Enumerating objects: 3453, done.
remote: Counting objects: 100% (707/707), done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 3453 (delta 311), reused 664 (delta 298), pack-reused 2746 (from 1)
Receiving objects: 100% (3453/3453), 791.32 MiB | 22.85 MiB/s, done.
Resolving deltas: 100% (1140/1140), done.
Updating files: 100% (1500/1500), done.
Downloading Checkpoints/CharacterGen/2D_Stage/models/checkpoint/scaler.pt (559 B)
Error downloading object: Checkpoints/CharacterGen/2D_Stage/models/checkpoint/scaler.pt (3c63c3d): Smudge error: Error downloading Checkpoints/CharacterGen/2D_Stage/models/checkpoint/scaler.pt (3c63c3d2e7b7f18788aca8a5a0e766ad4633f631d49192602d8532b6b0df7615): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\Users\nhb\stability_matrix\Packages\ComfyUI\custom_nodes\ComfyUI-3D-Pack\.git\lfs\logs\20241128T112544.9603087.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Checkpoints/CharacterGen/2D_Stage/models/checkpoint/scaler.pt: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The important part is:
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Only way is to get the lfs files from elsewhere I guess...

**Comment by MrForExample** [comment]
Hi all, I'm aware there is a problem wrt install from ComfyUI-Manager, as it doesn't seem will pull the newest Comfy3D version from github directly, I'll sort it out right after I integrated [TRELLIS](https://github.com/microsoft/TRELLIS) model

**Comment by gioxyer** [comment]
I tried also by git clone but give same issue

**Comment by DenisKochetov** [comment]
try to install the new version
