### ISSUE TITLE
Title: [Bug] FileNotFoundError during model download in ComfyUI 3D-Pack

### ISSUE THREAD

**Issue by godisme1220** [MrForExample/ComfyUI-3D-Pack#375]
```
Fetching 11 files:  27%|█████████████████▍                                              | 3/11 [01:50<04:54, 36.83s/it]
!!! Exception during processing !!! [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\Checkpoints\\Diffusers\\MrForExample\\Unique3D\\.cache\\huggingface\\download\\image2mvimage\\unet\\diffusion_pytorch_model.safetensors.93a3b4e678efac0c997e76df465df13136a4b0f1732e534a1200fad9e04cd0f9.incomplete'
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ...
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-3D-Pack\\Checkpoints\\Diffusers\\MrForExample\\Unique3D\\.cache\\huggingface\\download\\image2mvimage\\unet\\diffusion_pytorch_model.safetensors.93a3b4e678efac0c997e76df465df13136a4b0f1732e534a1200fad9e04cd0f9.incomplete'

```

I am encountering a FileNotFoundError while attempting to run the Unique3D project in ComfyUI. The error occurs during the download process of a model from Hugging Face. It seems the download was interrupted, leaving an incomplete file, and subsequent retries fail to resolve the issue.

**Comment by MrForExample** [comment]
Hi @godisme1220 sorry for the late responds
Load_Diffusers_Pipeline node should have a force_download option, if that is not working, then you can simply clean the HF cache
Cheers 👍
