### ISSUE TITLE
[BUG?] Era3D run failed

### ISSUE THREAD

**Issue by 2621690255** [MrForExample/ComfyUI-3D-Pack#379]
Problem info:
```
!!! Exception during processing !!! to() received an invalid combination of arguments - got (torch.dtype, dtype=torch.device), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)

Traceback (most recent call last):
  File "/home/user/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/user/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/user/anaconda3/envs/comfyui-py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 2595, in run_model
    multiview_images = images_pred.permute(0, 2, 3, 1).to(reference_image.dtype, dtype=reference_image.device)
TypeError: to() received an invalid combination of arguments - got (torch.dtype, dtype=torch.device), but expected one of:
 * (torch.device device = None, torch.dtype dtype = None, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (torch.dtype dtype, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
 * (Tensor tensor, bool non_blocking = False, bool copy = False, *, torch.memory_format memory_format = None)
```
**********************************************************************************************************************************

The Solution：
nodes.py > Era3D_MVDiffusion_Model > run_model
Line2595 and Line 2596
https://github.com/MrForExample/ComfyUI-3D-Pack/blob/c1718943d8e13844332c346285685681fdba3070/nodes.py#L2595
https://github.com/MrForExample/ComfyUI-3D-Pack/blob/c1718943d8e13844332c346285685681fdba3070/nodes.py#L2596

The source code:
```
        multiview_images = images_pred.permute(0, 2, 3, 1).to(reference_image.dtype, dtype=reference_image.device)   
        multiview_normals = normals_pred.permute(0, 2, 3, 1).to(reference_image.dtype, dtype=reference_image.device)
```
Maybe modify to:
```
        multiview_images = images_pred.permute(0, 2, 3, 1).to(dtype=reference_image.dtype, device=reference_image.device)   
        multiview_normals = normals_pred.permute(0, 2, 3, 1).to(dtype=reference_image.dtype, device=reference_image.device)
```

**Comment by MrForExample** [comment]
Hi @2621690255 I will fix this issue in next release 👍
