### ISSUE TITLE
Can not import name 'Bool' from 'jaxtyping'

### ISSUE THREAD

**Issue by gioxyer** [MrForExample/ComfyUI-3D-Pack#386]
After installing all the packages manually, I find this issue *'Can't import name 'Bool' from 'jaxtyping'**

C:\Users\giorg\Documents\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-28 07:17:38.270765
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\giorg\Documents\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.9 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 16310 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\web
C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:31: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kiui\nn\__init__.py:37: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_bwd

Traceback (most recent call last):
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 57, in <module>
    from TriplaneGaussian.triplane_gaussian_transformers import TGS
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\__init__.py", line 2, in <module>
    from .utils.typing import *
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\typing.py", line 31, in <module>
    from jaxtyping import Bool, Complex, Float, Inexact, Int, Integer, Num, Shaped, UInt
*'ImportError: cannot import name 'Bool' from 'jaxtyping'* (C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\jaxtyping\__init__.py)

Cannot import C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: cannot import name 'Bool' from 'jaxtyping' (C:\Users\giorg\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\jaxtyping\__init__.py)
Total VRAM 8192 MB, total RAM 16310 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Traceback (most recent call last):
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 18, in <module>
    from .liveportrait.live_portrait_pipeline import LivePortraitPipeline
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\live_portrait_pipeline.py", line 16, in <module>
    from .utils.filter import smooth
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\utils\filter.py", line 3, in <module>
    from pykalman import KalmanFilter
ModuleNotFoundError: No module named 'pykalman'

Cannot import C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ module for custom nodes: No module named 'pykalman'
Traceback (most recent call last):
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 1, in <module>
    from .nodes_registry import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\nodes_registry.py", line 4, in <module>
    from easy_nodes import initialize_easy_nodes
ModuleNotFoundError: No module named 'easy_nodes'

Cannot import C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'easy_nodes'
### ComfyUI Revision: 2866 [0d4e29f1] | Released on '2024-11-27'

Import times for custom nodes:
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\invert_mask_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\image_to_mask_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\saturation_ally.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\sharpness_ally.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\vae_decode_preview.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Pseudo_HDR_ally.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\mosaic_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\gaussian_blur_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\histogram_equalization.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\monocromatic_clip_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\image_to_contrast_mask_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\invert_image_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\brightness_contrast_ally.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\image2halftone.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\crop_node.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\imageflip_ally.py
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\gaussian_blur_ally.py
   0.0 seconds (IMPORT FAILED): C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM
   0.0 seconds (IMPORT FAILED): C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.0 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   8.6 seconds (IMPORT FAILED): C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: C:\Users\giorg\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by MrForExample** [comment]
Hi @gioxyer sorry for the late responds
That's weird, as you may probably solved right now, I would try first reinstalling the package, and if that do not work, then I would simply comment out the line 31 in `Gen_3D_Modules\TriplaneGaussian\utils\typing.py` as I just checked, type Bool is not really used anywhere. 
It should solve it, but, let me know if you have any other problem, cheers 👍
