### ISSUE TITLE
install fails 

### ISSUE THREAD

**Issue by Elminsst** [MrForExample/ComfyUI-3D-Pack#388]
File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI-K\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-K\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-K\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 82, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, multiview_color_projection_texture, get_cameras_list, get_orbit_cameras_list
  File "E:\ComfyUI-K\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 99, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-K\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 71, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\ops.py", line 228, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1314, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/1] "E:\ComfyUI-K\ComfyUI\.msvc\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64/link.exe" common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o /nologo /DLL /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\..\lib /DEFAULTLIB:gdi32 /DEFAULTLIB:opengl32 /DEFAULTLIB:user32 /DEFAULTLIB:setgpu c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" cudart.lib /out:nvdiffrast_plugin_gl.pyd

FAILED: nvdiffrast_plugin_gl.pyd 

"E:\ComfyUI-K\ComfyUI\.msvc\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64/link.exe" common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o /nologo /DLL /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\..\lib /DEFAULTLIB:gdi32 /DEFAULTLIB:opengl32 /DEFAULTLIB:user32 /DEFAULTLIB:setgpu c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" cudart.lib /out:nvdiffrast_plugin_gl.pyd

LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'

ninja: build stopped: subcommand failed.

Warn!: Cannot import E:\ComfyUI-K\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Error building extension 'nvdiffrast_plugin_gl': [1/1] "E:\ComfyUI-K\ComfyUI\.msvc\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64/link.exe" common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o /nologo /DLL /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\..\lib /DEFAULTLIB:gdi32 /DEFAULTLIB:opengl32 /DEFAULTLIB:user32 /DEFAULTLIB:setgpu c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" cudart.lib /out:nvdiffrast_plugin_gl.pyd

FAILED: nvdiffrast_plugin_gl.pyd 

"E:\ComfyUI-K\ComfyUI\.msvc\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64/link.exe" common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o /nologo /DLL /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\nvdiffrast\torch\..\lib /DEFAULTLIB:gdi32 /DEFAULTLIB:opengl32 /DEFAULTLIB:user32 /DEFAULTLIB:setgpu c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:E:\ComfyUI-K\ComfyUI\.ext\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\lib\x64" cudart.lib /out:nvdiffrast_plugin_gl.pyd

LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'

ninja: build stopped: subcommand failed.

how to fix this?

**Comment by MrForExample** [comment]
Hi @Elminsst, sorry for the late responds
There are a few nodes need runtime C++ compile
You can check if your [Visual Studio Build Tools 2022/2019 if installed correctly](https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Pre_Builds/README.md#build-for-windows)
And double click C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat

**Comment by Elminsst** [comment]
![image](https://github.com/user-attachments/assets/19369463-ed7e-4ba0-95dd-92aafafd030e)
Which of these options is correct?
Or do they all need to be installed?

**Comment by Elminsst** [comment]
![Uploading image.png…]()
Which of these options is correct?
Or do they all need to be installed?

**Comment by hirad** [comment]
@MrForExample I'm facing a similar issue on Linux. Any idea what the solution there might be?
