### ISSUE TITLE
Installation problems (again)

### ISSUE THREAD

**Issue by Kallamamran** [MrForExample/ComfyUI-3D-Pack#390]
For the fiftyeleventh time I have tried this installation. This time on a new system.
Installed latest ComfyUI with python 3.12.7, Torch 2.5.1+cu124 and cuda build cuda_1.4.r12.4/compiler.33961263_0

I have tried 

`.\python_embeded\python.exe q:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Scripts\auto_build_all.py`

Doesn't work. Gives me this:

```
Collecting OmegaConf
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting antlr4-python3-runtime==4.9.* (from OmegaConf)
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['ms', 'CCM', 'CSC', 'IME', 'INF', 'OCR', 'PLA', 'SKB', 'UDI', 'Vss', 'Web', 'Boot', 'Help', 'Logs', 'TAPI', 'Temp', 'WaaS', 'WWAN', 'debug', 'Fonts', 'Media', 'Setup', 'Tasks', 'addins', 'Speech', 'System', 'WinSxS', 'CbsTemp', 'Cursors', 'panther', 'schemas', 'tracing', 'wlansvc', 'apppatch', 'assembly', 'bcastdvr', 'Branding', 'ccmcache', 'ccmsetup', 'ELAMBKUP', 'Firmware', 'IMECache', 'Minidump', 'Prefetch', 'rescache', 'SchCache', 'security', 'System32', 'SysWOW64', 'twain_32', 'appcompat', 'DiagTrack', 'InboxApps', 'Installer', 'L2Schemas', 'Migration', 'ModemLogs', 'Resources', 'servicing', 'Containers', 'SystemApps', 'SystemTemp', 'diagnostics', 'IdentityCRL', 'InputMethod', 'Performance', 'PrintDialog', 'Screensaver', 'AppReadiness', 'Provisioning', 'Registration', 'ServiceState', 'DigitalLocker', 'Globalization', 'RemotePackages', 'Speech_OneCore', 'SensorFramework', 'ServiceProfiles', 'ShellComponents', 'SystemResources', 'ShellExperiences', 'LiveKernelReports', 'PolicyDefinitions', 'LanguageOverlayCache', 'SoftwareDistribution', 'GameBarPresenceWriter', 'ImmersiveControlPanel', 'BitLockerDiscoveryVolumeContents'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "q:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Scripts\build_utils.py", line 11, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "q:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Scripts\auto_build_all.py", line 11, in <module>
    from build_utils import (
  File "q:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds\_Build_Scripts\build_utils.py", line 14, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
```

Have tried installing omegaconf, but that doesn't work either. A similar error.

I have tried building the wheels manually from the correct version according to the link:

`https://github.com/MrForExample/Comfy3D_Pre_Builds/blob/main/_Build_Wheels/_Wheels_win_py312_torch2.5.1_cu124/torch_scatter-2.1.2-cp312-cp312-win_amd64.whl`

6/7 works, but the last one "pytorch3d-0.7.8-cp312-cp312-win_amd64.whl" gives me an error. The other ones builds just as they should.

I'm lost now. I have no idea how to continue or how to make this work. Nothing I have tried have managed to get me through one installation :(
Anyone?

**Comment by MrForExample** [comment]
Hi @Kallamamran , I'll try to help you in your [newest issue](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/392)
