### ISSUE TITLE
Installation problems again. ComfyUI 0.2.7 + v0.1.2

### ISSUE THREAD

**Issue by Kallamamran** [MrForExample/ComfyUI-3D-Pack#392]
```
Q:\ComfyUI_3D>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-09 09:51:12.957945
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: Q:\ComfyUI_3D\python_embeded\python.exe
** ComfyUI Path: Q:\ComfyUI_3D\ComfyUI
** Log path: Q:\ComfyUI_3D\comfyui.log

Prestartup times for custom nodes:
   1.6 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 130608 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 5000 Ada Generation Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: Q:\ComfyUI_3D\ComfyUI\web
Q:\ComfyUI_3D\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "Q:\ComfyUI_3D\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 4, in <module>
    from pyhocon import ConfigFactory
ModuleNotFoundError: No module named 'pyhocon'

Cannot import Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'pyhocon'
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Revision: 2808 [69667290] *DETACHED | Released on '2024-11-04'

Import times for custom nodes:
   0.0 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   0.4 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by Kallamamran** [comment]
Installed pyhocon manually by going into python_embedded and running ".\python.exe -m pip install pyhocon"
It installed without errors, but now I get this when starting ComfyUI instead:

```
Q:\ComfyUI_3D>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-09 10:23:57.419277
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: Q:\ComfyUI_3D\python_embeded\python.exe
** ComfyUI Path: Q:\ComfyUI_3D\ComfyUI
** Log path: Q:\ComfyUI_3D\comfyui.log

Prestartup times for custom nodes:
   1.7 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 130608 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX 5000 Ada Generation Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: Q:\ComfyUI_3D\ComfyUI\web
Q:\ComfyUI_3D\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "Q:\ComfyUI_3D\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 8, in <module>
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'

Cannot import Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'omegaconf'
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Revision: 2808 [69667290] *DETACHED | Released on '2024-11-04'

Import times for custom nodes:
   0.0 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   0.3 seconds: Q:\ComfyUI_3D\ComfyUI\custom_nodes\ComfyUI-Manager
```

**Comment by Kallamamran** [comment]
Trying to install OmegaConf of course doesn't work... As usual 😥

**Comment by MrForExample** [comment]
@Kallamamran Hi, I'm sure if you `.\python_embeded\python.exe -s -m pip install -r requirements.txt` then `.\python_embeded\python.exe install.py` then it would install all the necessary

let me know if you have any other problem, cheers 👍

**Comment by gerroon** [comment]
@MrForExample Thanks for the recommedation, but it doesn't work for me :( I am on Win 11.


`ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack>..\..\..\python_embeded\python.exe install.py`


```

ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack>..\..\..\python_embeded\python.exe install.py
Traceback (most recent call last):
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
    from build_utils import (
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
    CUDA_VERSION = get_cuda_version()
                   ^^^^^^^^^^^^^^^^^^
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 49, in get_cuda_version
    raise RuntimeError(f"Please install/reinstall CUDA tookit with any of the following supported version: {build_config.supported_cuda_versions}")
RuntimeError: Please install/reinstall CUDA tookit with any of the following supported version: ['12.4', '12.1', '11.8']
Traceback (most recent call last):
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 19, in <module>
    from build_utils import (
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 54, in <module>
    CUDA_VERSION = get_cuda_version()
                   ^^^^^^^^^^^^^^^^^^
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\_Pre_Builds/_Build_Scripts\build_utils.py", line 49, in get_cuda_version
    raise RuntimeError(f"Please install/reinstall CUDA tookit with any of the following supported version: {build_config.supported_cuda_versions}")
RuntimeError: Please install/reinstall CUDA tookit with any of the following supported version: ['12.4', '12.1', '11.8']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-3D-Pack\install.py", line 84, in <module>
    cstr("Comfy3D install failed: Dependency installation has failed. Please install manually: https://github.com/MrForExample/ComfyUI-3D-Pack/tree/main/_Pre_Builds/README.md.").error.print()
    ^^^^
NameError: name 'cstr' is not defined. Did you mean: 'str'?


```

**Comment by Mebemory** [comment]
@gerroon I had the same issue (Windows 11 too).
For a local fix:
1) Install CUDA Toolkit 12.4.
2) In `..\custom_nodes\ComfyUI-3D-Pack\install.py`, add and change the following lines:
![image](https://github.com/user-attachments/assets/3803665d-6d1a-41fc-89e2-2b81da81b8f0)
3) After that, running `\python_embedded\python.exe` install.py works without errors and downloads all necessary modules.
