### ISSUE TITLE
cant install - ComfyUI-3D-Pack (but all requirements met?)

### ISSUE THREAD

**Issue by iwannalikelinux** [MrForExample/ComfyUI-3D-Pack#400]
Hi, still new to Linux mint and I cant install ComfyUI-3D-Pack via the manger
i have 3060ti

I run through the requirements:
pip install -r /path/to/requirements.txt

in ComfyUI-3D-Pack folder
no issues with installing them

on starting ComfyUI > terminal states

18:56:56.727 [Warning] [ComfyUI-0/STDERR] Traceback (most recent call last):
18:56:56.727 [Warning] [ComfyUI-0/STDERR] File "/home/office/Desktop/SwarmUI v0.9.4.0/StableSwarmUI/dlbackend/ComfyUI/nodes.py", line 2072, in load_custom_node
18:56:56.727 [Warning] [ComfyUI-0/STDERR] module_spec.loader.exec_module(module)
18:56:56.727 [Warning] [ComfyUI-0/STDERR] File "", line 995, in exec_module
18:56:56.728 [Warning] [ComfyUI-0/STDERR] File "", line 488, in _call_with_frames_removed
18:56:56.728 [Warning] [ComfyUI-0/STDERR] File "/home/office/Desktop/SwarmUI v0.9.4.0/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-3D-Pack/init.py", line 53, in
18:56:56.728 [Warning] [ComfyUI-0/STDERR] module = importlib.import_module(f".{nodes_filename}", package=name)
18:56:56.728 [Warning] [ComfyUI-0/STDERR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:56:56.728 [Warning] [ComfyUI-0/STDERR] File "/usr/lib/python3.12/importlib/init.py", line 90, in import_module
18:56:56.728 [Warning] [ComfyUI-0/STDERR] return _bootstrap._gcd_import(name[level:], package, level)
18:56:56.728 [Warning] [ComfyUI-0/STDERR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 1387, in _gcd_import
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 1360, in _find_and_load
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 1331, in _find_and_load_unlocked
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 935, in _load_unlocked
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 995, in exec_module
18:56:56.729 [Warning] [ComfyUI-0/STDERR] File "", line 488, in _call_with_frames_removed
18:56:56.730 [Warning] [ComfyUI-0/STDERR] File "/home/office/Desktop/SwarmUI v0.9.4.0/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 38, in
18:56:56.730 [Warning] [ComfyUI-0/STDERR] from .mesh_processer.mesh import Mesh
18:56:56.730 [Warning] [ComfyUI-0/STDERR] File "/home/office/Desktop/SwarmUI v0.9.4.0/StableSwarmUI/dlbackend/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh.py", line 8, in
18:56:56.730 [Warning] [ComfyUI-0/STDERR] from kiui.op import safe_normalize, dot
18:56:56.730 [Warning] [ComfyUI-0/STDERR] ModuleNotFoundError: No module named 'kiui'
18:56:56.730 [Warning] [ComfyUI-0/STDERR]

Please can anyone help?
i want try all the 3d workflows but i cant get anything to run with the above issue..

**Comment by MrForExample** [comment]
Hi @iwannalikelinux, there is no pre-built wheels for Linux yet, at least not all of them, however if you install from ComfyUI-Manager or [manual install](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#install) build script will try to build all wheels automatically, please check [Semi-Automatic Build Guide](https://github.com/MrForExample/ComfyUI-3D-Pack/blob/main/_Pre_Builds/README.md#build-required-packages-semi-automatically) if you encountered any build error.

**Comment by SamTyurenkov** [comment]
this specific error is easily fixed with 

`YOUR_PYTHON_BINARY_PATH -m pip install kiui`

but you will face other missing libraries probably

**Comment by DenisKochetov** [comment]
try to install the new version please
