### ISSUE TITLE
error Trellis Image to mesh workflow

### ISSUE THREAD

**Issue by devrosx** [MrForExample/ComfyUI-3D-Pack#411]
Hello thanks for great nodes.. but i have error with Trellis node, any idea whats wrong 
looks like i cant compile nvdiffrast_plugin

`
(env) pc@pc-desktop:~/pinokio/cache/XDG_CACHE_HOME/torch_extensions/py310_cu121/nvdiffrast_plugin$ ls
Buffer.o  build.ninja  common.o  CudaRaster.o  RasterImpl.o  texture.o  torch_antialias.o  torch_bindings.o  torch_interpolate.o  torch_rasterize.o  torch_texture.o

(env) pc@pc-desktop:~/pinokio/cache/XDG_CACHE_HOME/torch_extensions/py310_cu121/nvdiffrast_plugin$ ninja
[1/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-o...ib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o
FAILED: RasterImpl.cuda.o
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output RasterImpl.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
`

 
`After decimate: 31393 vertices, 62653 faces
!!! Exception during processing !!! Error building extension 'nvdiffrast_plugin': [1/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output RasterImpl.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
FAILED: RasterImpl.cuda.o 
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output RasterImpl.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/cudaraster/impl/RasterImpl.cu -o RasterImpl.cuda.o 
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
[2/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output interpolate.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/interpolate.cu -o interpolate.cuda.o 
FAILED: interpolate.cuda.o 
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output interpolate.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/interpolate.cu -o interpolate.cuda.o 
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
[3/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output antialias.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/antialias.cu -o antialias.cuda.o 
FAILED: antialias.cuda.o 
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output antialias.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/antialias.cu -o antialias.cuda.o 
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
[4/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output rasterize.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/rasterize.cu -o rasterize.cuda.o 
FAILED: rasterize.cuda.o 
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output rasterize.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/rasterize.cu -o rasterize.cuda.o 
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
[5/6] /home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output texture.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/texture.cu -o texture.cuda.o 
FAILED: texture.cuda.o 
/home/pc/pinokio/bin/miniconda/bin/nvcc --generate-dependencies-with-compile --dependency-output texture.cuda.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/TH -isystem /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/include/THC -isystem /home/pc/pinokio/bin/miniconda/include -isystem /home/pc/pinokio/bin/miniconda/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -DNVDR_TORCH -lineinfo -std=c++17 -c /home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/nvdiffrast/common/texture.cu -o texture.cuda.o 
In file included from /home/pc/pinokio/bin/miniconda/include/cuda_runtime.h:83,
                 from <command-line>:
/home/pc/pinokio/bin/miniconda/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "/home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "/home/pc/pinokio/bin/miniconda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exi`

**Comment by devrosx** [comment]
ok found way to fix it...
`
cd ~/pinokio/cache/XDG_CACHE_HOME/torch_extensions/py310_cu121/nvdiffrast_plugin
sudo apt install gcc-12 g++-12
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12
rm -r *.o
ninja
`

then it works 👍

**Comment by devrosx** [comment]
but Trellis Image to mesh workflow still not working now i have this error
```
Removed 9047 faces by mincut
After remove invisible faces: 3895 vertices, 7786 faces
Rendering: 0it [00:00, ?it/s]
!!! Exception during processing !!! GaussianRasterizationSettings.__new__() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'
Traceback (most recent call last):
  File "/home/pc/pinokio/api/comfy.git/app/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/pc/pinokio/api/comfy.git/app/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/pc/pinokio/api/comfy.git/app/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/pc/pinokio/api/comfy.git/app/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/pc/pinokio/api/comfy.git/app/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 3973, in run_model
    vertices, faces, uvs, texture = postprocessing_utils.finalize_mesh(
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TRELLIS/trellis/utils/postprocessing_utils.py", line 451, in finalize_mesh
    observations, extrinsics, intrinsics = render_multiview(app_rep, resolution=1024, nviews=100)
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TRELLIS/trellis/utils/render_utils.py", line 106, in render_multiview
    res = render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': (0, 0, 0)})
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TRELLIS/trellis/utils/render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TRELLIS/trellis/renderers/gaussian_render.py", line 227, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
  File "/home/pc/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-3D-Pack/Gen_3D_Modules/TRELLIS/trellis/renderers/gaussian_render.py", line 77, in render
    raster_settings = GaussianRasterizationSettings(
TypeError: GaussianRasterizationSettings.__new__() missing 2 required positional arguments: 'kernel_size' and 'subpixel_offset'

end_vram - start_vram: 11464565432 - 6623836312 = 4840729120
#10 [[Comfy3D] Trellis Structured 3D Latents Models]: 8.07s - vram 4840729120b
Prompt executed in 8.08 seconds
[{'id': '10', 'time': 8.073337341000297, 'class_type': '[Comfy3D] Trellis Structured 3D Latents Models', 'vram_used': 4840729120}]
Printing Node Execution Times
+---------+------------------------------------------------+----------+-----------+
| Node ID | Type                                           | Time (s) | VRAM (GB) |
+---------+------------------------------------------------+----------+-----------+
| #10     | [Comfy3D] Trellis Structured 3D Latents Models | 8.07     | 4.51      |
| TOTAL   | -                                              | 8.54     | -         |
+---------+------------------------------------------------+----------+-----------+
No pending upload
```

**Comment by tcarneyjohnson** [comment]
Hello,

I'm using the Comfy3DPack by [YanWenKun](https://github.com/YanWenKun/Comfy3D-WinPortable) (maintaining the original 3D pack along with my other custom nodes was becoming impossible), but I encounter the same positional arguments error that you did. I was able to get around it by replacing the gaussian_render.py file located in C:...\Comfy3D_WinPortable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TRELLIS\trellis\renderers with the original file found here: https://github.com/microsoft/TRELLIS/blob/main/trellis/renderers/gaussian_render.py

Hope this helps.
