### ISSUE TITLE
I got this error installing pip install -r requirements_post.txt on Mac

### ISSUE THREAD

**Issue by fegoalbe** [MrForExample/ComfyUI-3D-Pack#46]
pip install -r requirements_post.txt
Processing ./tgs/models/snowflake/pointnet2_ops_lib
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/kq/_smxhsxd15d894bvmrfcx5ym0000gp/T/pip-build-env-g75lvbsa/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/kq/_smxhsxd15d894bvmrfcx5ym0000gp/T/pip-build-env-g75lvbsa/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/kq/_smxhsxd15d894bvmrfcx5ym0000gp/T/pip-build-env-g75lvbsa/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/kq/_smxhsxd15d894bvmrfcx5ym0000gp/T/pip-build-env-g75lvbsa/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(base) eduroam-int-dhcp-97-213-21:ComfyUI-3D-Pack-main albertofernandez2$

**Comment by DenisKochetov** [comment]
I didn't try it on a Mac, but have you tried a manual installation? In this [issue](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/13), there is a very good guide.
