### ISSUE TITLE
C++ Installation error

### ISSUE THREAD

**Issue by Luwolfx** [MrForExample/ComfyUI-3D-Pack#51]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Github\Luwolf-Aura-Bot\ai\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Luwolf-Aura-Bot\ai\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Luwolf-Aura-Bot\ai\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Luwolf-Aura-Bot\ai\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1339, in convert_gs_ply
    converter = GSConverterNeRFMarchingCubes(config_defaults[gs_config], gs_ply).cuda()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Github\Luwolf-Aura-Bot\ai\custom_nodes\ComfyUI-3D-Pack\algorithms\nerf_marching_cubes_converter.py", line 27, in __init__
    from kiui.gridencoder import GridEncoder
  File "D:\Github\Luwolf-Aura-Bot\ai\python_miniconda_env\ComfyUI\Lib\site-packages\kiui\gridencoder\__init__.py", line 1, in <module>
    from .grid import GridEncoder
  File "D:\Github\Luwolf-Aura-Bot\ai\python_miniconda_env\ComfyUI\Lib\site-packages\kiui\gridencoder\grid.py", line 9, in <module>
    from .backend import _backend
  File "D:\Github\Luwolf-Aura-Bot\ai\python_miniconda_env\ComfyUI\Lib\site-packages\kiui\gridencoder\backend.py", line 41, in <module>
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

**Comment by Luwolfx** [comment]
I don't know what could be the error with the C++ instalation

**Comment by stefania1708** [comment]
> I don't know what could be the error with the C++ instalation

I had the same error. 
In the script backend.py, at line 33, the code is trying to find the folder where cl.exe is:
paths = sorted(glob.glob(r"C:\\Program Files (x86)\\Microsoft Visual Studio\\*\\%s\\VC\\Tools\\MSVC\\*\\bin\\Hostx64\\x64" % edition), reverse=True)

In my case, I had Visual Studio installed in a completely different path so yeah...you can change the line with your own path or edit the environment variables.
