### ISSUE TITLE
How do I generate images that can be used to generate models?

### ISSUE THREAD

**Issue by Coconut8201** [MrForExample/ComfyUI-3D-Pack#55]
I want to try to generate a model using my own images, but I get an error:
RuntimeError: The size of tensor a (1000) must match the size of tensor b (64) at non-singleton dimension 1. 

The following is my process:

Command: python main.py

Total VRAM 24215 MB, total RAM 128578 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090: cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
/home/ethci/Projects/ComfyUI/custom_nodes/ComfyUI-3D-Pack/lgm/core/attention.py:22: UserWarning: xFormers is available (Attention)
   warnings.warn("xFormers is available (Attention)")
/home/ethci/Projects/ComfyUI/ComfyUI/lib/python3.11/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree .register_pytree_node instead.
   torch.utils._pytree._register_pytree_node(

Import times for custom nodes:
    0.6 seconds: /home/ethci/Projects/ComfyUI/custom_nodes/ComfyUI-3D-Pack

Starting server

To see the GUI go to: http://163.13.201.153:8188
got prompt
Keyword arguments {'trust_remote_code': True} are not expected by MVDreamPipeline and will be ignored.
Loading pipeline components...: 100%|﻿﻿﻿﻿﻿﻿| 7/7 [00:00<00:00, 22.36it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
   File "/home/ethci/Projects/ComfyUI/execution.py", line 152, in recursive_execute
     output_data, output_ui = get_output_data(obj, input_data_all)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/ethci/Projects/ComfyUI/execution.py", line 82, in get_output_data
     return_values ​​= map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/ethci/Projects/ComfyUI/execution.py", line 75, in map_node_over_list
     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^
   File "/home/ethci/Projects/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 1210, in run_mvdream
     reference_image = (reference_image * reference_mask + (1 - reference_mask)).detach().cpu().numpy()
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (1000) must match the size of tensor b (64) at non-singleton dimension 1

Prompt executed in 1.53 seconds

**Comment by MrForExample** [comment]
Hi, you can try to make the image square and make it sure your mask and image have the same width and height

**Comment by Coconut8201** [comment]
Hello, I later discovered that it can be successfully generated by removing the back of the image and adjusting it to a square shape with a size less than 1000.
