### ISSUE TITLE
No module named 'diff_gaussian_rasterization'

### ISSUE THREAD

**Issue by ctankep** [MrForExample/ComfyUI-3D-Pack#6]
Hi ,

This looks interesting and `pip install -r requirements.txt`   
went fine. Then on running " comfy ui " the `diff_gaussian_rasterization`     
module can't be imported in `main_3dgs_renderer' ..

How can I install `diff_gaussian_rasterization'  , which seems to be a
submodule of the INRIA 'gaussian splitting' repo ? I'll try installing from
that repo though this has the actual code :
[ [https://github.com/graphdeco-inria/diff-gaussian-rasterization](https://github.com/graphdeco-inria/diff-gaussian-rasterization) ]

```
** ComfyUI startup time: 2024-01-31 15:27:10.696087
** Platform: Windows
** Python version: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
** Python executable: C:\Users\chuan_l\AppData\Local\Programs\Python\Python310\python.exe

Traceback (most recent call last):
  File "C:\Users\chuan_l\Documents\Repo\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\chuan_l\Documents\Repo\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "C:\Users\chuan_l\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\chuan_l\Documents\Repo\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 19, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GSParams
  File "C:\Users\chuan_l\Documents\Repo\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 11, in <module>
    from .main_3DGS_renderer import Renderer
  File "C:\Users\chuan_l\Documents\Repo\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 26, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import C:\Users\chuan_l\Documents\Repo\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'
```

Thanks !

**Comment by MrForExample** [comment]
Did you run the install.bat? 
Please follow the [install instruction](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#install) for how to install `diff_gaussian_rasterization `and other necessary packages

**Comment by al3dv2** [comment]
Hi, I have the same problem and I've run the install.bat please helps thanks

**Comment by al3dv2** [comment]
Ok installing cuda-12.1.0 fix the bug
