### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by davedaverave** [MrForExample/ComfyUI-3D-Pack#60]
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 19, in <module>
    from .mesh_processer.mesh_utils import (
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 3, in <module>
    from kornia.geometry.conversions import (
ImportError: cannot import name 'quaternion_to_axis_angle' from 'kornia.geometry.conversions' (/usr/local/lib/python3.9/dist-packages/kornia/geometry/conversions.py)

**Comment by DenisKochetov** [comment]
Did you try to upgrade kornia lib? 
`pip install --upgrade kornia`
