### ISSUE TITLE
ImportError: simple_knn undefined symbol

### ISSUE THREAD

**Issue by signorinileandro** [MrForExample/ComfyUI-3D-Pack#63]
I'm getting this error on Ubuntu 22.04:

`Traceback (most recent call last):
  File "/home/leandro/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "/home/leandro/miniconda3/envs/gensei/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 26, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI-3D-Pack/algorithms/main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "/home/leandro/ComfyUI/custom_nodes/ComfyUI-3D-Pack/algorithms/main_3DGS_renderer.py", line 28, in <module>
    from simple_knn._C import distCUDA2
ImportError: /home/leandro/miniconda3/envs/gensei/lib/python3.10/site-packages/simple_knn/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops4full4callEN3c108ArrayRefINS2_6SymIntEEERKNS2_6ScalarENS2_8optionalINS2_10ScalarTypeEEENS9_INS2_6LayoutEEENS9_INS2_6DeviceEEENS9_IbEE

Cannot import /home/leandro/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: /home/leandro/miniconda3/envs/gensei/lib/python3.10/site-packages/simple_knn/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops4full4callEN3c108ArrayRefINS2_6SymIntEEERKNS2_6ScalarENS2_8optionalINS2_10ScalarTypeEEENS9_INS2_6LayoutEEENS9_INS2_6DeviceEEENS9_IbEE
`

**Comment by hggz** [comment]
I had to rollback and install kiuiu @ 0.23 instead of the latest 0.24. It doesn't fix all the issues tho, just gets over this one

**Comment by hggz** [comment]
On second thought, I think you might need to make sure you're running with cuda12.1. I ran into this with other dependencies when using cuda 11.8

**Comment by ClothingAI** [comment]
Lmao, this extension produce SO MUCH so MANY errors!
I had many and I just found this one. I will try your downgrade of kiuiu and see.

**Comment by ClothingAI** [comment]
Wait I was already at  kiui  0.2.13,
dont know if i should modify it. in this case. (I am on Torch 2.4.0cu121)
