### ISSUE TITLE
Can't find main.py with Miniconda

### ISSUE THREAD

**Issue by mothormothormothor** [MrForExample/ComfyUI-3D-Pack#65]
I'm getting an error when opening the `run_nvidia_gpu_miniconda.bat` file. It says the file`main.py` is not there, but it is. I noticed that it somehow "doubles" the ComfyUI folder although there is only one. (see red mark in screenshot)
I don't know that much about code but I think I managed to install everything properly. Anybody has an idea what could cause this issue?

`![error_conda](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/105822353/32db32d7-cac3-4956-8646-d9710165c63f)

When running with the alternative method, I can avoid the "double" ComfyUI folder, but get the following error message: 

```
C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>conda activate python_miniconda_env\ComfyUI

(C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\python_miniconda_env\ComfyUI) C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>python ./main.py
Traceback (most recent call last):
  File "C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\comfy\utils.py", line 5, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'

(C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\python_miniconda_env\ComfyUI) C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>

```

**Comment by MrForExample** [comment]
> I'm getting an error when opening the `run_nvidia_gpu_miniconda.bat` file. It says the file`main.py` is not there, but it is. I noticed that it somehow "doubles" the ComfyUI folder although there is only one. (see red mark in screenshot) I don't know that much about code but I think I managed to install everything properly. Anybody has an idea what could cause this issue?
> 
> `![error_conda](https://private-user-images.githubusercontent.com/105822353/308974702-32db32d7-cac3-4956-8646-d9710165c63f.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzYxMzksIm5iZiI6MTcwOTIzNTgzOSwicGF0aCI6Ii8xMDU4MjIzNTMvMzA4OTc0NzAyLTMyZGIzMmQ3LWNhYzMtNDk1Ni04NjQ2LWQ5NzEwMTY1YzYzZi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxOTQzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTMwNTZkMjBmNWI3NDMxY2YwYzRhYzAyOTIwMjI5NmNiZGM4ZWUzNDcyNzQ2ZGUzMmVkMzIxYmM3MzNmZmFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MJzCxCO_Xq_mQeaPIg2LTUO56eclZnYOOdwlnaHHNSM)
> 
> When running with the alternative method, I can avoid the "double" ComfyUI folder, but get the following error message:
> 
> ```
> C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>conda activate python_miniconda_env\ComfyUI
> 
> (C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\python_miniconda_env\ComfyUI) C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>python ./main.py
> Traceback (most recent call last):
>   File "C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\main.py", line 73, in <module>
>     import comfy.utils
>   File "C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\comfy\utils.py", line 5, in <module>
>     import safetensors.torch
> ModuleNotFoundError: No module named 'safetensors'
> 
> (C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI\python_miniconda_env\ComfyUI) C:\Users\Marvin\Desktop\CreativeCoding\ComfyUI>
> ```

Hi friend you have to put run_nvidia_gpu_miniconda.bat under your ComfyUI root directory like:
![Screenshot 2024-02-29 205340](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/62230687/a11964f7-41dd-4f92-baf9-7ce3bdc9cb1a)

And if you missing "safetensors" or other packages then please use `[Your ComfyUI python.exe path] pip install --force-reinstall [package name]`

**Comment by mothormothormothor** [comment]
Hi @MrForExample thank you! I managed to get an proper installation but when running `run_nvidia_gpu_miniconda.bat` I get the following message and nodes are missing:

```
Traceback (most recent call last):
  File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Marvin\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 26, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 7, in <module>
    from kiui.cam import orbit_camera
ModuleNotFoundError: No module named 'kiui'

Cannot import C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
```

![error_miniconda_run_bat](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/105822353/392deb79-6904-4bfc-8115-79d6905975f5)

**Comment by hggz** [comment]
yeah I got this following the same setup instructions. I havent been able to get this reliably setup with either the windows portable environment or miniconda. Miniconda gives me this

**Comment by lovisdotio** [comment]
> Hi @MrForExample thank you! I managed to get an proper installation but when running `run_nvidia_gpu_miniconda.bat` I get the following message and nodes are missing:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
>     module = importlib.import_module(f".{nodes_filename}", package=__name__)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Marvin\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 26, in <module>
>     from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 7, in <module>
>     from kiui.cam import orbit_camera
> ModuleNotFoundError: No module named 'kiui'
> 
> Cannot import C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
> ```
> 
> ![error_miniconda_run_bat](https://private-user-images.githubusercontent.com/105822353/309482989-392deb79-6904-4bfc-8115-79d6905975f5.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0OTYxMTAsIm5iZiI6MTcwOTQ5NTgxMCwicGF0aCI6Ii8xMDU4MjIzNTMvMzA5NDgyOTg5LTM5MmRlYjc5LTY5MDQtNGJmYy04MTE1LTc5ZDY5MDU5NzVmNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxOTU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjhiNDhlMTczYzg0ZmRjMDg4MWNjNGQ0NWJmYjRkMGRiOGNiNjNhZjY5ODZhZGUxZWFhMjQ2YWY1ZjU3MTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hOS2OuW-cgyGlsffnuOyCW_PNfvCnltWh3A0KeRizEg)

same error without using conda, but directly in ubunut

**Comment by MrForExample** [comment]
> Hi @MrForExample thank you! I managed to get an proper installation but when running `run_nvidia_gpu_miniconda.bat` I get the following message and nodes are missing:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
>     module = importlib.import_module(f".{nodes_filename}", package=__name__)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Marvin\ComfyUI_windows_portable\python_miniconda_env\ComfyUI\Lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 26, in <module>
>     from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
>   File "C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 7, in <module>
>     from kiui.cam import orbit_camera
> ModuleNotFoundError: No module named 'kiui'
> 
> Cannot import C:\Users\Marvin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
> ```
> 
> ![error_miniconda_run_bat](https://private-user-images.githubusercontent.com/105822353/309482989-392deb79-6904-4bfc-8115-79d6905975f5.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NzI4MjYsIm5iZiI6MTcwOTU3MjUyNiwicGF0aCI6Ii8xMDU4MjIzNTMvMzA5NDgyOTg5LTM5MmRlYjc5LTY5MDQtNGJmYy04MTE1LTc5ZDY5MDU5NzVmNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxNzE1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OGFmZjdhZGQ0MzQ4MTdkNmMyYzRjMjBiMDkyYjU2ZTdmNjU4NWNmMmUwZTA5M2ZjNzY1NmE5NmVlOTgzZTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GsktAnzq9bdYXC5-WYn2uQJYv0IbdPRyn6zdiaOih2o)

Hi, that error means you didn't install the cuda packages inside the requirements_post.txt, try `pip install -r requirements_post.txt`, also please double check the [install guide](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#install-method-1-using-minicondaworks-on-windows--linux--mac)
