### ISSUE TITLE
None of the example workflows aren't working

### ISSUE THREAD

**Issue by hggz** [MrForExample/ComfyUI-3D-Pack#70]
I haven't been able to successfully run any of the example workflows

I get this error (both on linux and the portable windows install)

`class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]`

I tried updating using the provided batch scripts to no avail

**Comment by MrForExample** [comment]
Hi, you may want to check [this issue](https://github.com/MrForExample/ComfyUI-3D-Pack/issues/61) first,
And if you still can't resolve the error, then can I have your full console error log pls? This is not enough information.

**Comment by hggz** [comment]
@MrForExample thank you so much for your efforts and apologies for the lack luster initial post. It was really late and I was fading into the night 😅

I did checkout that issue and think this is a different issue, something to do with the worfklows missing nodes on ComfyUI for some reason (following the install steps with theportable windows install).

Attached are some logs and what I'm seeing from within the portable windows install (on windows 10, with the VS tools 2022, running a 3090)

```
To see the GUI go to: http://127.0.0.1:8188
got prompt
Error handling request
Traceback (most recent call last):
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hggz\Documents\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 626, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'
```

WONDER_3D_to_large workflow:
![wonder3d_to_large_](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/6015420/04368da6-0936-417c-b705-bbad1b8cc15d)

![wonder3d_to_large_error1](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/6015420/0c25d97e-1fd1-4a74-87ef-31fa0ea72c1d)

TRIPLANE WORKFLOW:
![triplane_error_json](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/6015420/24251ab9-a5b1-451d-a41c-75eed77bb50a)

![triplane_error_launch](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/6015420/ed4c9480-6c38-449a-82bf-8ec7342508c8)


USING STACKBIT WORKFLOW:
![using_stack_orbit_error](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/6015420/8eaba1be-c9dc-427e-9679-ccd5c271a189)


Also (on a side note) I'm working on a portable docker version of this which already builds but gives me some Floating point (expected 4 but got 2) errors in the CUDA enabled ` Wonder3D_to_Large_Multiview_Gaussian_Model_to_3DGS and_3DMesh` example so maybe its a dependency problem?

**Comment by anvenle** [comment]
I also encountered the same problem in these workflow（like fig 1）. I think there are missing files somewhere, and I don’t know where to download the missing files（like fig 2，3）.
I still encountered a issue when starting up（fig 4，5）
![wonder3d](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/147358581/4a9609e8-abd6-492a-8e6a-e8729dddf928)
![LGM](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/147358581/647c11c1-ccae-43d2-a8d6-f4377f2257c6)
![lgm (2)](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/147358581/f3ff64e1-198f-4895-bbac-a005ca7add1d)
![main](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/147358581/b12303c0-3f85-4bb1-a2fa-43fe51455fe1)
![1709631675007](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/147358581/4a4e919b-8c2f-4b86-9421-932c49c15dba)

**Comment by dkebude** [comment]
Hi @MrForExample, I have the exact same problem (without the missing `/.ipynb_checkpoints/_init__.py`). This occurs on most workflows, I could only get TripoSR pipeline to work as of now. Are there any pointers you could give and is there anything I can help with?

**Comment by DenisKochetov** [comment]
try to install the new version
