### ISSUE TITLE
ComfyUI-Flowty-TripoSR brake everything 

### ISSUE THREAD

**Issue by kakachiex2** [MrForExample/ComfyUI-3D-Pack#76]
I update your extension and this happens do I have to recompiled everything

 File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 40, in <module>
    from .lgm.mvdream.pipeline_mvdream import MVDreamPipeline
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-3D-Pack\lgm\mvdream\pipeline_mvdream.py", line 7, in <module>
    from diffusers import AutoencoderKL, DiffusionPipeline
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: AMD Ryzen 7 2700X Eight-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 2060
[Crystools INFO] NVIDIA Driver: 546.33
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter\nodes.py", line 3, in <module>
    from diffusers import DPMSolverMultistepScheduler
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
Module 'diffusers' not installed. Please install it via:
pip install diffusers
Comfy-Easy-Use (v1.1.0): Loaded
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO\__init__.py", line 7, in <module>
    from tsr.utils import remove_background, resize_foreground
ImportError: cannot import name 'remove_background' from 'tsr.utils' (K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\utils.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO module for custom nodes: cannot import name 'remove_background' from 'tsr.utils' (K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR\tsr\utils.py)
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\__init__.py", line 1, in <module>
    from .I2VGenXL import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\I2VGenXL.py", line 9, in <module>
    from diffusers import I2VGenXLPipeline
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-I2VGenXL module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 1, in <module>
    import diffusers
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\__init__.py", line 1, in <module>
    from .layered_diffusion import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\layered_diffusion.py", line 17, in <module>
    from .lib_layerdiffusion.models import TransparentVAEDecoder
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-layerdiffusion\lib_layerdiffusion\models.py", line 9, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-layerdiffusion module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
### ComfyUI Revision: 2046 [a38b9b3a] | Released on '2024-03-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
 ### Mixlab Nodes: Loaded
## lama torchscript model not found: K:\ComfyUI\ComfyUI_Ex\ComfyUI\models\lama/big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
## clip_interrogator_model not found: K:\ComfyUI\ComfyUI_Ex\ComfyUI\models\clip_interrogator/Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## zh_en_model not found: K:\ComfyUI\ComfyUI_Ex\ComfyUI\models\prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
 --------------
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO\__init__.py", line 1, in <module>
    from .PhotoMakerNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO\PhotoMakerNode.py", line 5, in <module>
    from diffusers.utils import load_image
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)

Cannot import K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO module for custom nodes: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\huggingface_hub\constants.py)
[ReActor] - STATUS - Running v0.4.1-b11 in ComfyUI
Torch version: 2.2.0+cu121
3D OpenPose Editor: Loaded
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 59 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (7) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
K:\ComfyUI\ComfyUI_Ex\ComfyUI\web\extensions\failfast-comfyui-extensions
2024-03-05 20:52:29.099 | WARNING  | Jovimetrix.nodes.utility:<module>:49 - no gifski support

[rgthree] Loaded 34 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Total VRAM 6144 MB, total RAM 65488 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
VAE dtype: torch.float32

Import times for custom nodes:
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\kohya_hiresfix.py
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\Lora-Training-in-Comfy
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\Image-Captioning-in-ComfyUI
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_3dPoseEditor
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR-ZHO
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-SVD-ZHO
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Selector-CoInput-Multilingual
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\CrasHUtils
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Diffusers-X-Adapter
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-I2VGenXL
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-layerdiffusion
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Flowty-TripoSR
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.3 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI_Seg_VITON
   0.5 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.6 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Manager
   0.9 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\a-person-mask-generator
   1.3 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-SUPIR
   1.5 seconds (IMPORT FAILED): K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   1.6 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\Jovimetrix
   2.4 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   3.1 seconds: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-Crystools

**Comment by Ratinod** [comment]
I also needed to save a backup of the python_embeded folder...

**Comment by kakachiex2** [comment]
Ok I fixed everything works know

**Comment by kakachiex2** [comment]
were is the tripodSR model is downloaded because I already have it were the extension look for it, I name it tripodSR

**Comment by kakachiex2** [comment]
Sorry sorry for the inconvenience why I'm getting this result any tips, could it be the BRIA background remover image format
![Screenshot 2024-03-05 235630](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/881073aa-b2f8-4713-a36f-03cf4246838a)

**Comment by kakachiex2** [comment]
And can you add the option to load the model from normal checkpoint model location I dont want to have duplicate model all over.

**Comment by kakachiex2** [comment]
And there is a bug every time I change the picture the generate model don't update keep the same 3d model.

**Comment by kakachiex2** [comment]
I restart ComfyUI and know it generate the image ok but it don't update the 3d view if I change to another image and render keep the same model.
![Screenshot 2024-03-06 024955](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/1762112/33e1a850-eda9-4e34-a5b8-a2a819be45c3)

**Comment by MrForExample** [comment]
> I restart ComfyUI and know it generate the image ok but it don't update the 3d view if I change to another image and render keep the same model. ![Screenshot 2024-03-06 024955](https://private-user-images.githubusercontent.com/1762112/310390986-33e1a850-eda9-4e34-a5b8-a2a819be45c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTY0MDIsIm5iZiI6MTcwOTcxNjEwMiwicGF0aCI6Ii8xNzYyMTEyLzMxMDM5MDk4Ni0zM2UxYTg1MC1lZGE5LTRlMzQtYTViOC1hMmE4MTliZTQ1YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDkwODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVjYjBlNGRmMDFmMTEwZTVjNDhiNTk1NmE2OGY1NThhMWY4ODU1MjQxODIzMDM0YmY2ZDc4ZmIzMzEwNDJhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lAxeDclkmXo4Uba4AHE5UEKk8a-pRMffzr3rmlcPZJQ)

Hi friend, thanks for testing, I'm aware of that bug, I'll trying to fix it in the next update, for now, if you give the saved model a different name then it will reload it, cheers

**Comment by kakachiex2** [comment]
If you see in the screenshot I'm using your node and thanks for reply

**Comment by Dragoy** [comment]
> I restart ComfyUI and know it generate the image ok but it don't update the 3d view if I change to another image and render keep the same model. ![Screenshot 2024-03-06 024955](https://private-user-images.githubusercontent.com/1762112/310390986-33e1a850-eda9-4e34-a5b8-a2a819be45c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDE3ODIsIm5iZiI6MTcxMDkwMTQ4MiwicGF0aCI6Ii8xNzYyMTEyLzMxMDM5MDk4Ni0zM2UxYTg1MC1lZGE5LTRlMzQtYTViOC1hMmE4MTliZTQ1YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjBUMDIyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM4NTFkOGQ4MmQ1ZjE0NzQ4NmVhMzMwYWRhODRiZjQwM2JlNzQzZWUwMmU0OTFiNmNiZDkxNjkxZTRiY2ZlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5ezCdGzz87quqsbv1B6S9Yd21j2rUdMbUP5geKAbFHs)

Так же столкнулся с проблемой выполнения этого воркфлоу: 

`Error occurred when executing [Comfy3D] TripoSR:

Cannot handle this data type: (1, 1, 5), |u1

File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 1655, in run_TSR
image = Image.fromarray(np.clip(255. * image, 0, 255).astype(np.uint8))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 5), |u1`

[workflow-triposr-image_2_3d_wf_v101-9f3rDM4m7YQXTsWmvRk6-kakachiex-openart.ai (1).json](https://github.com/MrForExample/ComfyUI-3D-Pack/files/14661472/workflow-triposr-image_2_3d_wf_v101-9f3rDM4m7YQXTsWmvRk6-kakachiex-openart.ai.1.json)

**Comment by DenisKochetov** [comment]
try to install the new version
