### ISSUE TITLE
ImportError: DLL load failed while importing _C

### ISSUE THREAD

**Issue by tiandaoyuxi** [MrForExample/ComfyUI-3D-Pack#77]
Traceback (most recent call last):
  File "D:\ComfyUI_NEW\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_NEW\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_NEW\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 28, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "D:\ComfyUI_NEW\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "D:\ComfyUI_NEW\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
  File "D:\ComfyUI_NEW\python_embeded\Lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: 找不到指定的模块。

Cannot import D:\ComfyUI_NEW\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: DLL load failed while importing _C: 找不到 指定的模块。

**Comment by laitianwen** [comment]
请问解决了吗？ 我也出现了这个问题？

**Comment by laitianwen** [comment]
Have you solved it? I have this problem too?

**Comment by criskb** [comment]
i have this aswell

**Comment by MrForExample** [comment]
Hi, may I ask you which method did you use to install this tool? (Embed env with pre-build wheels or Miniconda), Also where and how did you download this package? Because it should be ComfyUI-3D-Pack\__init__.py instead of ComfyUI-3D-Pack_init.py

**Comment by crowtalons** [comment]
same here. embed env with wheels. I have correct __init__.py filename but the same exact error:

Traceback (most recent call last):
  File "S:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 33, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "S:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "S:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
  File "S:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: The specified module could not be found.

**Comment by crowtalons** [comment]
okay turns out I'm a dumbasss and did not have VS build tools. downloaded those, re-installed the addon and it works. hope maybe that helps someone else as well.

**Comment by Scharwunzel** [comment]
Hi crowtalons,
which Visual Studio tool did you install that made the difference?
I have the same error message and checked my VS and couldn't find any build that was missing...

**Comment by Scharwunzel** [comment]
@crowtalons, thank you very much for the quick answer.
I already had VS on my computer before Stable Diffusion or comfyui, and C++ was already installed. I also updated everything and looked through the individual builds.
So that can't be the cause of the error for me.
I'll open a new thread about this, I don't know what else to do.
Kind regards

**Comment by Huajijunbilibili** [comment]
Have you solved it? I have this problem too。

**Comment by GPU-server** [comment]
me too.
