### ISSUE TITLE
Installation does not work. fix please <3

### ISSUE THREAD

**Issue by quantumbalance** [MrForExample/ComfyUI-3D-Pack#81]
Hey. this seems so cool but alas it wouldn't install with the portable version or the non portable version. although i am a dumb ape. please fix. thank you

**Comment by Falkonar** [comment]
Should we install miniconda before everything? And how files appear in ComfyUI\custom_nodes ? Using install manager or download from this repo and copy manually? So much missing in instructions. Thank you anyway, I hope this is really splats inside COmfyUi finally )

**Comment by Falkonar** [comment]
First Install VS 2019 and C++ desktop tools 
Second Install VS 2022 and  C++ desktop tools
Next Install Cuda 12.1

When I use install_windows_portable_win_py311_cu121.bat

1 - xformers-0.0.24-cp311-cp311-win_amd64.whl (205.4 MB)
2 - torch-2.2.0%2Bcu121-cp311-cp311-win_amd64.whl (2454.8 MB)
3 - (error) - torchvision 0.17.1+cu121 requires torch==2.2.1+cu121, but you have torch 2.2.0+cu121 which is incompatible. 

I try miniconda - same result 
I try anaconda3 - same result
I try manual install from Issue #22 - the same result

I spend 8 hours straight . Help please

**Comment by Falkonar** [comment]
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack>pip install -r requirements_post.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing c:\comfyui_windows_portable\comfyui\custom_nodes\comfyui-3d-pack\tgs\models\snowflake\pointnet2_ops_lib
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\tgs\models\snowflake\pointnet2_ops_lib\setup.py", line 20, in <module>
          os.environ["TORCH_CUDA_ARCH_LIST"] = ".".join(map(str, torch.cuda.get_device_capability()))
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MPG\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 439, in get_device_capability
          prop = get_device_properties(device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\MPG\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 453, in get_device_properties
          _lazy_init()  # will define _get_device_properties
          ^^^^^^^^^^^^
        File "C:\Users\MPG\anaconda3\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
          raise AssertionError("Torch not compiled with CUDA enabled")
      AssertionError: Torch not compiled with CUDA enabled
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by quantumbalance** [comment]
🤮 fix your crap dev

**Comment by MrForExample** [comment]
> First Install VS 2019 and C++ desktop tools Second Install VS 2022 and C++ desktop tools Next Install Cuda 12.1
> 
> When I use install_windows_portable_win_py311_cu121.bat
> 
> 1 - xformers-0.0.24-cp311-cp311-win_amd64.whl (205.4 MB) 2 - torch-2.2.0%2Bcu121-cp311-cp311-win_amd64.whl (2454.8 MB) 3 - (error) - torchvision 0.17.1+cu121 requires torch==2.2.1+cu121, but you have torch 2.2.0+cu121 which is incompatible.
> 
> I try miniconda - same result I try anaconda3 - same result I try manual install from Issue #22 - the same result
> 
> I spend 8 hours straight . Help please

Hi friend, apologies for bad package management, so many things has happened to me recently, I'm doing my best to use my free time to do what I can to help 👍 

Having said that, in your case, however, it seems the problem is caused by newest version of torch not compatible with old version of torchvision, that problem can be simply solved by:

Reinstall torch==2.2.0+cu121 torchvision==0.17.0+cu121: 
- If you are using ComfyUI embed Python env: 
`Path to your ComfyUI python embed python.exe path -s -m pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`
- If you are using Miniconda/Conda, after activate your conda environment: 
`pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`

**Comment by Falkonar** [comment]
> > First Install VS 2019 and C++ desktop tools Second Install VS 2022 and C++ desktop tools Next Install Cuda 12.1
> > When I use install_windows_portable_win_py311_cu121.bat
> > 1 - xformers-0.0.24-cp311-cp311-win_amd64.whl (205.4 MB) 2 - torch-2.2.0%2Bcu121-cp311-cp311-win_amd64.whl (2454.8 MB) 3 - (error) - torchvision 0.17.1+cu121 requires torch==2.2.1+cu121, but you have torch 2.2.0+cu121 which is incompatible.
> > I try miniconda - same result I try anaconda3 - same result I try manual install from Issue #22 - the same result
> > I spend 8 hours straight . Help please
> 
> Hi friend, apologies for bad package management, so many things has happened to me recently, I'm doing my best to use my free time to do what I can to help 👍
> 
> Having said that, in your case, however, it seems the problem is caused by newest version of torch not compatible with old version of torchvision, that problem can be simply solved by:
> 
> Reinstall torch==2.2.0+cu121 torchvision==0.17.0+cu121:
> 
> * If you are using ComfyUI embed Python env:
>   `Path to your ComfyUI python embed python.exe path -s -m pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`
> * If you are using Miniconda/Conda, after activate your conda environment:
>   `pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`

1 (python) run_nvidia_gpu.bat
result -  No module named 'rembg' (IMPORT FAILED)
2 (miniconda) run_nvidia_gpu_miniconda.bat
relust -   No module named 'chardet'

Press any key to continue . . .

Please create the new setup instructions for noobs...  . And no luck running on Debian too (((

**Comment by Falkonar** [comment]
> > First Install VS 2019 and C++ desktop tools Second Install VS 2022 and C++ desktop tools Next Install Cuda 12.1
> > When I use install_windows_portable_win_py311_cu121.bat
> > 1 - xformers-0.0.24-cp311-cp311-win_amd64.whl (205.4 MB) 2 - torch-2.2.0%2Bcu121-cp311-cp311-win_amd64.whl (2454.8 MB) 3 - (error) - torchvision 0.17.1+cu121 requires torch==2.2.1+cu121, but you have torch 2.2.0+cu121 which is incompatible.
> > I try miniconda - same result I try anaconda3 - same result I try manual install from Issue #22 - the same result
> > I spend 8 hours straight . Help please
> 
> Hi friend, apologies for bad package management, so many things has happened to me recently, I'm doing my best to use my free time to do what I can to help 👍
> 
> Having said that, in your case, however, it seems the problem is caused by newest version of torch not compatible with old version of torchvision, that problem can be simply solved by:
> 
> Reinstall torch==2.2.0+cu121 torchvision==0.17.0+cu121:
> 
> * If you are using ComfyUI embed Python env:
>   `Path to your ComfyUI python embed python.exe path -s -m pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`
> * If you are using Miniconda/Conda, after activate your conda environment:
>   `pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121`

1 (python) run_nvidia_gpu.bat
result -  No module named 'rembg' (IMPORT FAILED)
2 (miniconda) run_nvidia_gpu_miniconda.bat
relust -   No module named 'chardet'

Press any key to continue . . .

Please create the new setup instructions for noobs...  . And no luck running on Debian too (((

**Comment by zewolf5** [comment]
What i normally do as a quick check before throwing in the gauntlet and asking. If python says "No module named 'xxxxx'" then i do a 
pip install xxxxx

Then either that works or your stuck. But here I am sure it will solve your problem. Was missing for me too.

**Comment by Falkonar** [comment]
> What i normally do as a quick check before throwing in the gauntlet and asking. If python says "`No module named 'xxxxx'`" then i do a `pip install xxxxx`
> 
> Then either that works or your stuck. But here I am sure it will solve your problem. Was missing for me too.
> 
> The trick above with `pip install --force-reinstall torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121` and then `pip install rembg` solved it.
> 
> I did have to a `pip install --force-reinstall fsspec==2023.5.0` as there was a huggingface red text on imcompatibility.
> 
> and a `pip install xformers` as it wasnt there

Thank you so much for chewing me up. I'm really trying, but I wasn't attentive enough. The thing is that half a year ago I was just a 3D artist, but today I'm studying computer vision to keep up with the times. The endless errors are very nerve-wracking, but it's an endless buzz when the code works. Thanks again.
