### ISSUE TITLE
ImportError: cannot import name 'quaternion_to_axis_angle' from 'kornia.geometry.conversions

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [MrForExample/ComfyUI-3D-Pack#87]
Hello tribe I hope you all are doing well.

so I am attempting to install with runpod and just fast dreambooth notebook.

i get this error

ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-3D-Pack/__init__.py", line 18, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-3D-Pack/nodes.py", line 21, in <module>
    from .mesh_processer.mesh_utils import (
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-3D-Pack/mesh_processer/mesh_utils.py", line 3, in <module>
    from kornia.geometry.conversions import (
ImportError: cannot import name 'quaternion_to_axis_angle' from 'kornia.geometry.conversions' (/usr/local/lib/python3.10/dist-packages/kornia/geometry/conversions.py)

Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-3D-Pack module for custom nodes: cannot import name 'quaternion_to_axis_angle' from 'kornia.geometry.conversions' (/usr/local/lib/python3.10/dist-packages/kornia/geometry/conversions.py)

anyone know how to fix it.

**Comment by MrForExample** [comment]
Hi friend

You may have a old kornia version installed, try: `Your comfy python.exe path -s -m pip install --force-reinstall kornia`

**Comment by dwgeneral** [comment]
> Hi friend
> 
> You may have a old kornia version installed, try: `Your comfy python.exe path -s -m pip install --force-reinstall kornia`

this make my ComfyUI broken

**Comment by javideas** [comment]
were you able to run this on runpod?
