### ISSUE TITLE
AttributeError: 'list' object has no attribute 'write'

### ISSUE THREAD

**Issue by DorotaLuna** [MrForExample/ComfyUI-3D-Pack#90]
Remove the image background, link the image to TripoSR, then clipck the queue prompt.
py311, win11

Here is the workflow
![image](https://github.com/MrForExample/ComfyUI-3D-Pack/assets/122320001/bab51285-d819-4966-a78a-a1c190f2f3d9)

And here is the log
```
got prompt
[Comfy3D] [Save_3D_Mesh] Saving model to C:\AI\Blender_ComfyUI\ComfyUI\output\Mesh_2024-03-11-25-37-846416.obj
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\AI\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 253, in save_mesh
    mesh.write(save_path)
    ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'write'

Prompt executed in 0.02 seconds
```

**Comment by MrForExample** [comment]
Hi friend, you are using flowty's  addon, which is not compatible with Comfy3D, you can using TripoSR node provided by Comfy3D instead, please check example workflow for how to use it 👍
