### ISSUE TITLE
diff_gaussian_rasterization error

### ISSUE THREAD

**Issue by filliptm** [MrForExample/ComfyUI-3D-Pack#93]
Traceback (most recent call last):
  File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "C:\Users\Filli\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 28, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'

im running the non local version of comfy, installed the requirements.txt, running into this error

**Comment by MrForExample** [comment]
Hi @filliptm 

If you installed it manually, then you'll also need to install `requirements_post.txt`
Please check [Install Guide](https://github.com/MrForExample/ComfyUI-3D-Pack?tab=readme-ov-file#install) for details
