### ISSUE TITLE
Loading error. What can it be?

### ISSUE THREAD

**Issue by vkleinmp** [MrForExample/ComfyUI-3D-Pack#95]
Web extensions folder found at C:\Users\vali\pinokio\api\comfyui.git\app\web\extensions\ComfyLiterals
Traceback (most recent call last):
  File "C:\Users\vali\pinokio\api\comfyui.git\app\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\vali\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 28, in <module>     
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
  File "C:\Users\vali\pinokio\bin\miniconda\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\vali\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 30, in <module>        
    from .algorithms.main_3DGS import GaussianSplatting, GaussianSplattingCameraController, GSParams
  File "C:\Users\vali\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 12, in <module>
    from .main_3DGS_renderer import GaussianSplattingRenderer
  File "C:\Users\vali\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 24, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import C:\Users\vali\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'

**Comment by DenisKochetov** [comment]
Did you install it?
```
git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
pip install ./diff-gaussian-rasterization
```

**Comment by ZSURBO** [comment]
> Did you install it?
> 
> ```
> git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization
> pip install ./diff-gaussian-rasterization
> ```

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects
